-- CAMPI VARCHAR
-- o specifico char nella definizione o non metto niente perchè in automatico oracle li definisce a char

-- INDICI
-- se colonna su cui fare l'indice é già PK, lui se lo fa in automatico, quindi non é necessario specificarlo


-- ***********************************************************************************************
--          DROP
-- ***********************************************************************************************

DROP TABLE OPP_ESITI_APP_ANAGRAFICHE;
DROP TABLE OPP_ESITI_APP_UTENTI;
DROP TABLE OPP_ESITI_APP_UBA;
DROP TABLE OPP_ESITI_APP_UBA_AMM;
DROP TABLE OPP_ESITI_APP_NATURA_2000;
DROP TABLE OPP_ESITI_APP_ESITO_SUP;
DROP TABLE OPP_ESITI_APP_ESITO_IMPEGNI;
DROP TABLE OPP_ESITI_APP_ESITO_COND_ATTO;
DROP TABLE OPP_ESITI_APP_ESITO_COND;
DROP TABLE OPP_ESITI_APP_CAPI_ALLEVATI;
DROP TABLE OPP_ESITI_APP_CAMPIONE;
DROP TABLE OPP_ESITI_DWH_INT_SOTTOINT;
DROP TABLE OPP_ESITI_APP_CONTROLLO;
DROP TABLE OPP_ESITI_APP_ESITO_SUP_BKP;
DROP TABLE OPP_ESITI_APP_DOMANDA_DU;
DROP TABLE OPP_ESITI_APP_AZIENDA_DU;
DROP TABLE OPP_ESITI_APP_CODICI_COND;
DROP TABLE OPP_ESITI_APP_TUTELA_ACQUE;
DROP TABLE OPP_ESITI_APP_AZIENDA;
DROP TABLE OPP_ESITI_APP_DOMANDA;
DROP TABLE OPP_ESITI_DWH_MATR_AMM_IDEALE;
DROP TABLE OPP_ESITI_APP_ZOOT_STATO;
DROP TABLE OPP_ESITI_APP_ZOOT_ESI_AMM_BOV;
DROP TABLE APP_ZOOT_ESI_AMM_BOV_INT;
DROP TABLE OPP_ESITI_APP_ZOOT_ESI_AMM_OVI;
DROP TABLE OPP_ESITI_APP_ZOOT_CTR_AMM_BOV;
DROP TABLE OPP_ESITI_APP_ZOOT_CTR_AMM_OVI;
DROP TABLE OPP_ESITI_APP_ZOOT_CTR_COND;
DROP TABLE OPP_ESITI_APP_ESITO_RM_FIT_FER;
DROP TABLE OPP_ESITI_APP_ESITO_FITFER_EXT;
DROP TABLE OPP_ESITI_APP_ESITO_IMP_EXT;


purge recyclebin;


-- ***********************************************************************************************
--          TABELLA DWH.....
-- ***********************************************************************************************


CREATE TABLE "OPP_ESITI_DWH_INT_SOTTOINT"(
"CUAA" VARCHAR(20 CHAR),
"DOMANDA_AGEA" VARCHAR(15 CHAR),
"DOMANDA_OPR" VARCHAR(15 CHAR)  ,
"INTERVENTO" VARCHAR(10 CHAR),
"DESCR_INTERVENTO" VARCHAR(200 CHAR),
"SOTTOINTERVENTO" VARCHAR(10 CHAR),
"DESCR_SOTTOINT" VARCHAR(200 CHAR) , 
"DATA_INSERIMENTO" TIMESTAMP DEFAULT SYSDATE NOT NULL ENABLE,
"USER_INSERIMENTO" VARCHAR(30 CHAR), 
"MISURA" VARCHAR(10 CHAR)
) NOLOGGING TABLESPACE OPP_ESITI_TAB;

-- INDICI
CREATE INDEX IDX_INT_SOTTOINT_CUAA ON OPP_ESITI_DWH_INT_SOTTOINT (CUAA ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;
CREATE INDEX IDX_INT_SOTTOINT_DOMANDA_AGEA ON OPP_ESITI_DWH_INT_SOTTOINT (DOMANDA_AGEA ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;
CREATE INDEX IDX_INT_SOTTOINT_DOMANDA_OPR ON OPP_ESITI_DWH_INT_SOTTOINT (DOMANDA_OPR ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;
--INDICE SULLA PK
CREATE INDEX IDX_INT_SOTTOINT_PK ON OPP_ESITI_DWH_INT_SOTTOINT (CUAA, MISURA, DOMANDA_OPR, INTERVENTO, SOTTOINTERVENTO ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;

--PK
ALTER TABLE OPP_ESITI_DWH_INT_SOTTOINT 
    ADD CONSTRAINT OPP_ESITI_DWH_INT_SOTTOINT_PK PRIMARY KEY ( CUAA, MISURA, DOMANDA_OPR, INTERVENTO, SOTTOINTERVENTO ) USING INDEX IDX_INT_SOTTOINT_PK;

    
-- ***********************************************************************************************


  CREATE TABLE "OPP_ESITI_ADM"."OPP_ESITI_DWH_MATR_AMM_IDEALE" 
   (	"CUAA" VARCHAR2(20 CHAR), 
	"CAMPAGNA" NUMBER, 
	"ATTO_A1" VARCHAR2(5 CHAR), 
	"ATTO_A2" VARCHAR2(5 CHAR), 
	"ATTO_A3" VARCHAR2(5 CHAR), 
	"ATTO_A4" VARCHAR2(5 CHAR), 
	"ATTO_FER" VARCHAR2(5 CHAR), 
	"ATTO_A5" VARCHAR2(5 CHAR), 
	"ATTO_A6" VARCHAR2(5 CHAR), 
	"ATTO_A7" VARCHAR2(5 CHAR), 
	"ATTO_A8" VARCHAR2(5 CHAR), 
	"ATTO_B9" VARCHAR2(5 CHAR), 
	"ATTO_FIT" VARCHAR2(5 CHAR), 
	"ATTO_B10" VARCHAR2(5 CHAR), 
	"ATTO_B11" VARCHAR2(5 CHAR), 
	"ATTO_B12" VARCHAR2(5 CHAR), 
	"ATTO_B13" VARCHAR2(5 CHAR), 
	"ATTO_B14" VARCHAR2(5 CHAR), 
	"ATTO_B15" VARCHAR2(5 CHAR), 
	"ATTO_C16" VARCHAR2(5 CHAR), 
	"ATTO_C17" VARCHAR2(5 CHAR), 
	"ATTO_C18" VARCHAR2(5 CHAR), 
	"ATTO_1_1" VARCHAR2(5 CHAR), 
	"ATTO_1_2" VARCHAR2(5 CHAR), 
	"ATTO_1_3" VARCHAR2(5 CHAR), 
	"ATTO_2_1" VARCHAR2(5 CHAR), 
	"ATTO_2_2" VARCHAR2(5 CHAR), 
	"ATTO_3_1" VARCHAR2(5 CHAR), 
	"ATTO_4_1" VARCHAR2(5 CHAR), 
	"ATTO_4_2" VARCHAR2(5 CHAR), 
	"ATTO_4_3" VARCHAR2(5 CHAR), 
	"ATTO_4_4" VARCHAR2(5 CHAR), 
	"ATTO_4_6" VARCHAR2(5 CHAR), 
	"ATTO_5_1" VARCHAR2(5 CHAR), 
	"ATTO_5_2" VARCHAR2(5 CHAR),
	"ATTO_CGO1" VARCHAR2(5 CHAR),
    "ATTO_BCAA1" VARCHAR2(5 CHAR),
    "ATTO_BCAA2" VARCHAR2(5 CHAR),
    "ATTO_BCAA3" VARCHAR2(5 CHAR),
    "ATTO_BCAA4" VARCHAR2(5 CHAR),
    "ATTO_BCAA5" VARCHAR2(5 CHAR),
    "ATTO_BCAA6" VARCHAR2(5 CHAR),
    "ATTO_CGO2" VARCHAR2(5 CHAR),
    "ATTO_CGO3" VARCHAR2(5 CHAR),
    "ATTO_BCAA7" VARCHAR2(5 CHAR),
    "ATTO_CGO4" VARCHAR2(5 CHAR),
    "ATTO_CGO5" VARCHAR2(5 CHAR),
    "ATTO_CGO6" VARCHAR2(5 CHAR),
    "ATTO_CGO7" VARCHAR2(5 CHAR), 
    "ATTO_CGO8" VARCHAR2(5 CHAR),
    "ATTO_CGO9" VARCHAR2(5 CHAR),
    "ATTO_CGO10" VARCHAR2(5 CHAR),
    "ATTO_CGO11" VARCHAR2(5 CHAR),
    "ATTO_CGO12" VARCHAR2(5 CHAR),
    "ATTO_CGO13" VARCHAR2(5 CHAR),
    "ATTO_BCAA8" VARCHAR2(5 CHAR),
	"USER_INSERIMENTO" VARCHAR(30 CHAR),
	"DATA_INSERIMENTO" TIMESTAMP DEFAULT SYSDATE NOT NULL ENABLE	
   ) NOLOGGING TABLESPACE "OPP_ESITI_TAB" ;
 
--INDICE SULLA PK
CREATE INDEX IDX_MATR_AMM_PK ON OPP_ESITI_DWH_MATR_AMM_IDEALE (CUAA, CAMPAGNA ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;

--PK
ALTER TABLE OPP_ESITI_DWH_MATR_AMM_IDEALE 
    ADD CONSTRAINT IDX_MATR_AMM_PK PRIMARY KEY ( CUAA, CAMPAGNA ) USING INDEX IDX_MATR_AMM_PK;

    
-- ***********************************************************************************************
--          TABELLA APP.....
-- ***********************************************************************************************

  CREATE TABLE "OPP_ESITI_APP_ANAGRAFICHE" (	
  "CAMPO" VARCHAR2(100 CHAR), 
	"VALORE" VARCHAR2(255 CHAR), 
	"NOTE" VARCHAR2(500 CHAR), 
	"USER_INSERIMENTO" VARCHAR2(50 CHAR), 
	"DATA_INSERIMENTO" DATE DEFAULT sysdate, 
	"USER_MODIFICA" VARCHAR2(50 CHAR), 
	"DATA_MODIFICA" DATE, 
	"CAMPAGNA_INIZIO_VAL" NUMBER DEFAULT to_char(sysdate, 'YYYY'), 
	"CAMPAGNA_FINE_VAL" NUMBER DEFAULT 9999
   ) NOLOGGING TABLESPACE  "OPP_ESITI_TAB" ;
   
-- INDICE PK
CREATE INDEX IDX_ANAGRAFICHE_PK ON OPP_ESITI_APP_ANAGRAFICHE (CAMPO, VALORE, CAMPAGNA_INIZIO_VAL, CAMPAGNA_FINE_VAL ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;

--PK
ALTER TABLE OPP_ESITI_APP_ANAGRAFICHE 
    ADD CONSTRAINT OPP_ESITI_APP_ANAGRAFICHE_PK PRIMARY KEY ( CAMPO, VALORE, CAMPAGNA_INIZIO_VAL, CAMPAGNA_FINE_VAL ) USING INDEX IDX_ANAGRAFICHE_PK;

-- COMMENTO DELLA TABELLA
COMMENT ON TABLE "OPP_ESITI_APP_ANAGRAFICHE"
IS 'Tabella che gestisce tutte le anagrafiche dell applicazione';

-- ***********************************************************************************************

CREATE TABLE "OPP_ESITI_APP_AZIENDA" (
  "CUAA" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"RAGIONE_SOCIALE" VARCHAR2(255 CHAR), 
	"PROVINCIA" VARCHAR2(255 CHAR), 
	"LOCALITA" VARCHAR2(255 CHAR),
	"DATA_INSERIMENTO" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
	"USER_INSERIMENTO" VARCHAR2(50 CHAR), 
	"DATA_MODIFICA" TIMESTAMP (6), 
	"USER_MODIFICA" VARCHAR2(50 CHAR), 
	"SORGENTE" VARCHAR2(50 CHAR)
   ) NOLOGGING TABLESPACE OPP_ESITI_TAB;
   
-- INDICE PK
CREATE INDEX IDX_AZIENDA_ALL_CUAA ON OPP_ESITI_APP_AZIENDA (CUAA ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;

--PK
ALTER TABLE OPP_ESITI_APP_AZIENDA 
    ADD CONSTRAINT OPP_ESITI_APP_AZIENDA_ALL_PK PRIMARY KEY ( CUAA ) USING INDEX IDX_AZIENDA_ALL_CUAA;

-- COMMENTO DELLA TABELLA
COMMENT ON TABLE "OPP_ESITI_APP_AZIENDA"
IS 'Tabella che gestisce tutte le aziende, sia provienienti dal fascicolo che inserite a mano';

-- ***********************************************************************************************

CREATE TABLE "OPP_ESITI_APP_AZIENDA_DU"(
"CUAA" VARCHAR(20 CHAR) NOT NULL ENABLE, -- PK
"RAGIONE_SOCIALE" VARCHAR(255 CHAR)  ,
"PROVINCIA" VARCHAR(255 CHAR) ,
"LOCALITA" VARCHAR(255 CHAR) ,
"DATA_INSERIMENTO" TIMESTAMP DEFAULT SYSDATE NOT NULL ENABLE,
"USER_INSERIMENTO" VARCHAR(50 CHAR),
"DATA_MODIFICA" TIMESTAMP ,
"USER_MODIFICA" VARCHAR(50 CHAR)
) NOLOGGING TABLESPACE OPP_ESITI_TAB;

-- INDICE PK
CREATE INDEX IDX_AZIENDA_DU_CUAA ON OPP_ESITI_APP_AZIENDA_DU (CUAA ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;

--PK
ALTER TABLE OPP_ESITI_APP_AZIENDA_DU 
    ADD CONSTRAINT OPP_ESITI_APP_AZIENDA_DU_PK PRIMARY KEY ( CUAA ) USING INDEX IDX_AZIENDA_DU_CUAA;

-- COMMENTO DELLA TABELLA
COMMENT ON TABLE "OPP_ESITI_APP_AZIENDA_DU"
IS 'Tabella che gestisce le aziende inserite manualmente dagli utenti';

-- ***********************************************************************************************

CREATE TABLE "OPP_ESITI_APP_CAMPIONE" (
  "DOMANDA_OPR" VARCHAR2(15 CHAR) NOT NULL ENABLE, 
	"CUAA" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"CAMPAGNA" NUMBER, 
	"CATEGORIA_CAMPIONE" VARCHAR2(50 CHAR), 
	"TIPO_CAMPIONE" VARCHAR2(20 CHAR), 
	"DATA_CAMPIONE" DATE, 
	"DOMINIO_CAMP_COND" VARCHAR2(200 CHAR), 
	"STATO_DOMANDA_OPPAB" VARCHAR2(200 CHAR), 
	"NOTE" VARCHAR2(500 CHAR),
	"ORIGINE_CAMPIONE" VARCHAR2(50 CHAR),
	"BOVINI" VARCHAR2(50 CHAR), 
	"OVICAPRINI" VARCHAR2(50 CHAR), 
    "DATA_INSERIMENTO" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
	"USER_INSERIMENTO" VARCHAR2(50 CHAR), 
	"DATA_MODIFICA" TIMESTAMP (6), 
	"USER_MODIFICA" VARCHAR2(50 CHAR)
) NOLOGGING TABLESPACE OPP_ESITI_TAB;

-- INDICI
CREATE INDEX IDX_CAMPIONE_DOMANDA ON OPP_ESITI_APP_CAMPIONE (DOMANDA_OPR ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;
CREATE INDEX IDX_CAMPIONE_CUAA ON OPP_ESITI_APP_CAMPIONE (CUAA ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;
-- INDICE PK
CREATE INDEX IDX_CAMPIONE_PK ON OPP_ESITI_APP_CAMPIONE (CUAA, DOMANDA_OPR, CAMPAGNA, CATEGORIA_CAMPIONE ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;

--PK
ALTER TABLE OPP_ESITI_APP_CAMPIONE 
    ADD CONSTRAINT OPP_ESITI_APP_CAMPIONE_PK PRIMARY KEY ( DOMANDA_OPR, CAMPAGNA , CATEGORIA_CAMPIONE) USING INDEX IDX_CAMPIONE_PK;

-- COMMENTO DELLA TABELLA
COMMENT ON TABLE "OPP_ESITI_APP_CAMPIONE"
IS 'Tabella che gestisce le informazioni del campione';

-- ***********************************************************************************************

CREATE TABLE "OPP_ESITI_APP_CAPI_ALLEVATI" (
"CUAA" VARCHAR(20 CHAR) NOT NULL ENABLE,
"CAMPAGNA" NUMBER, 
"BOVINI" VARCHAR(10 CHAR),
"BUFALINI" VARCHAR(10 CHAR),
"CAPRINI" VARCHAR(10 CHAR),
"EQUINI" VARCHAR(10 CHAR),
"OVINI" VARCHAR(10 CHAR),
"SUINI" VARCHAR(10 CHAR),
"DATA_INSERIMENTO" TIMESTAMP DEFAULT SYSDATE NOT NULL ENABLE,
"USER_INSERIMENTO" VARCHAR(30 CHAR),
"DATA_MODIFICA" TIMESTAMP,
"USER_MODIFICA" VARCHAR(30 CHAR)
) NOLOGGING TABLESPACE OPP_ESITI_TAB;

-- INDICE PK
CREATE INDEX IDX_CAPI_ALLEVATI_PK ON OPP_ESITI_APP_CAPI_ALLEVATI (CUAA, CAMPAGNA ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;

--PK
ALTER TABLE OPP_ESITI_APP_CAPI_ALLEVATI 
    ADD CONSTRAINT OPP_ESITI_APP_CAPI_ALLEVATI_PK PRIMARY KEY ( CUAA, CAMPAGNA ) USING INDEX IDX_CAPI_ALLEVATI_PK;


-- ***********************************************************************************************

CREATE TABLE "OPP_ESITI_APP_CODICI_COND" (
"COD_COND" VARCHAR(10 CHAR), 
"ATTO_NORMA" VARCHAR(10 CHAR), -- PK
"DESCR_ATTO" VARCHAR(500 CHAR),
"DATA_INSERIMENTO" TIMESTAMP DEFAULT SYSDATE NOT NULL ENABLE,
"USER_INSERIMENTO" VARCHAR(50 CHAR),
"DATA_MODIFICA" TIMESTAMP ,
"USER_MODIFICA" VARCHAR(50 CHAR),
"CAMPAGNA_INIZIO" NUMBER,
"CAMPAGNA_FINE" NUMBER,
"FLG_VALIDITA" VARCHAR(1 CHAR)
)  NOLOGGING TABLESPACE OPP_ESITI_TAB;

-- INDICI
CREATE INDEX IDX_COD_COND_ATTO_NORMA ON OPP_ESITI_APP_CODICI_COND (ATTO_NORMA ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;
CREATE INDEX IDX_COD_COND_COD_COND ON OPP_ESITI_APP_CODICI_COND (COD_COND ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;
-- INDICE PK
CREATE INDEX IDX_COD_COND_PK ON OPP_ESITI_APP_CODICI_COND (COD_COND, ATTO_NORMA ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;

--PK 
ALTER TABLE OPP_ESITI_APP_CODICI_COND 
    ADD CONSTRAINT OPP_ESITI_APP_CODICI_COND_PK PRIMARY KEY ( COD_COND, ATTO_NORMA ) USING INDEX IDX_COD_COND_PK ;
	
-- COMMENTO DELLA TABELLA
COMMENT ON TABLE "OPP_ESITI_APP_CODICI_COND"
IS 'Tabella che gestisce le anagrafiche dei codici di condizionalita';


-- ***********************************************************************************************

CREATE TABLE "OPP_ESITI_APP_CONTROLLO" (
"CUAA" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
"CAMPAGNA" NUMBER, 
"DATA_PREAVVISO" VARCHAR2(15 CHAR), 
"DATA_INIZIO_CONTROLLO" VARCHAR2(15 CHAR), 
"DATA_FINE_CONTROLLO" VARCHAR2(15 CHAR), 
"CONTROLLORE" VARCHAR2(100 CHAR), 
"TIPO_CONTROLLO" VARCHAR2(100 CHAR), 
"TIPO_PREAVVISO" VARCHAR2(100 CHAR),
"PERSONA_PRESENTE" VARCHAR2(50 CHAR),
"NOME_DELEGATO" VARCHAR2(100 CHAR), 
"NUMERO_DOCUMENTO_DELEGATO" VARCHAR2(100 CHAR), 
"DATA_INSERIMENTO" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
"USER_INSERIMENTO" VARCHAR2(50 CHAR), 
"DATA_MODIFICA" TIMESTAMP (6), 
"USER_MODIFICA" VARCHAR2(50 CHAR)
) NOLOGGING TABLESPACE OPP_ESITI_TAB;

-- INDICI
CREATE INDEX IDX_CONTROLLO_CUAA_PK ON OPP_ESITI_APP_CONTROLLO (CUAA, CAMPAGNA ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;

--PK
ALTER TABLE OPP_ESITI_APP_CONTROLLO 
    ADD CONSTRAINT OPP_ESITI_APP_CONTROLLO_PK PRIMARY KEY ( CUAA, CAMPAGNA ) USING INDEX IDX_CONTROLLO_CUAA_PK;

COMMENT ON TABLE "OPP_ESITI_APP_CONTROLLO"
IS 'tabella che contiene i dati generici del controllo complessivo, indipendentemente dal tipo di campione ';

-- ***********************************************************************************************

CREATE TABLE "OPP_ESITI_APP_DOMANDA" (
"CUAA" VARCHAR2(20 CHAR), 
"CAMPAGNA" NUMBER, 
"DOMANDA_AGEA" VARCHAR2(15 CHAR), 
"DOMANDA_OPR" VARCHAR2(15 CHAR), 
"MISURA" VARCHAR2(10 CHAR), 
"IMP_RICH" NUMBER, 
"IMP_LIQ" NUMBER, 
"DATA_INSERIMENTO" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
"USER_INSERIMENTO" VARCHAR2(50 CHAR), 
"DATA_MODIFICA" TIMESTAMP (6), 
"USER_MODIFICA" VARCHAR2(50 CHAR)
 ) NOLOGGING TABLESPACE OPP_ESITI_TAB;

-- INDICE PK
CREATE INDEX IDX_DOMANDA_ALL_PK ON OPP_ESITI_APP_DOMANDA (DOMANDA_OPR, MISURA ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;

--PK
ALTER TABLE OPP_ESITI_APP_DOMANDA 
    ADD CONSTRAINT OPP_ESITI_APP_DOMANDA_ALL_PK PRIMARY KEY ( DOMANDA_OPR, MISURA ) USING INDEX IDX_DOMANDA_ALL_PK ;

COMMENT ON TABLE "OPP_ESITI_APP_DOMANDA"
IS 'tabella che contiene tutte le domande PSR e DU';

-- ***********************************************************************************************

CREATE TABLE "OPP_ESITI_APP_DOMANDA_DU"(
"CUAA" VARCHAR2(20 CHAR), 
"CAMPAGNA" NUMBER, 
"DOMANDA" VARCHAR2(15 CHAR), 
"IMP_RICH" NUMBER, 
"IMP_LIQ_NETTO_MOD" NUMBER, 
"DATA_INSERIMENTO" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
"USER_INSERIMENTO" VARCHAR2(50 CHAR), 
"DATA_MODIFICA" TIMESTAMP (6), 
"USER_MODIFICA" VARCHAR2(50 CHAR)
) NOLOGGING TABLESPACE OPP_ESITI_TAB;

-- INDICE PK
CREATE INDEX IDX_DOMANDA_DU_PK ON OPP_ESITI_APP_DOMANDA_DU (CAMPAGNA, CUAA, DOMANDA ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;

--PK
ALTER TABLE OPP_ESITI_APP_DOMANDA_DU 
    ADD CONSTRAINT OPP_ESITI_APP_DOMANDA_DU_PK PRIMARY KEY ( CAMPAGNA, CUAA, DOMANDA ) USING INDEX IDX_DOMANDA_DU_PK ;

COMMENT ON TABLE "OPP_ESITI_APP_DOMANDA_DU"
IS 'tabella che contiene tutte le domande DU inserite dagli utenti';

-- ***********************************************************************************************
     
CREATE TABLE "OPP_ESITI_APP_ESITO_COND"(
"CUAA" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
"CAMPAGNA" NUMBER, 
"DATA_CAMPIONE" VARCHAR2(50 CHAR), 
"DATA_CONTROLLO" VARCHAR2(50 CHAR), 
"ESITO_FINALE" VARCHAR2(8 CHAR), 
"RID_PERC_PSR" VARCHAR2(20 CHAR), 
"RID_PERC_DU" VARCHAR2(20 CHAR), 
"STATO" VARCHAR2(50 CHAR), 
"NOTE" VARCHAR2(500 CHAR), 
"DATA_INSERIMENTO" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
"USER_INSERIMENTO" VARCHAR2(50 CHAR), 
"DATA_MODIFICA" TIMESTAMP (6), 
"USER_MODIFICA" VARCHAR2(50 CHAR), 
NUMERO_DECRETO VARCHAR2(50 CHAR),
DATA_DECRETO date,
NOTE_DECRETO VARCHAR2(500 CHAR)
) NOLOGGING TABLESPACE OPP_ESITI_TAB;

--INDICI
--CREATE INDEX IDX_ESITO_COND_CUAA ON OPP_ESITI_APP_ESITO_COND (CUAA ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;
--CREATE INDEX IDX_ESITO_COND_CAMPAGNA ON OPP_ESITI_APP_ESITO_COND (CAMPAGNA ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;
-- INDICE PK
CREATE INDEX IDX_ESITO_COND_PK ON OPP_ESITI_APP_ESITO_COND (CUAA, CAMPAGNA ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;
--PK
ALTER TABLE OPP_ESITI_APP_ESITO_COND 
    ADD CONSTRAINT OPP_ESITI_APP_ESITO_COND_PK PRIMARY KEY ( CUAA, CAMPAGNA ) USING INDEX IDX_ESITO_COND_PK;

COMMENT ON TABLE "OPP_ESITI_APP_ESITO_COND"
IS 'tabella che contiene gli esiti dei controlli di condiizonalita per azienda';

-- ***********************************************************************************************

CREATE TABLE "OPP_ESITI_APP_ESITO_COND_ATTO" (
"CUAA" VARCHAR2(20 CHAR), 
"CAMPAGNA" NUMBER(*,0), 
"COD_COND" VARCHAR2(10 CHAR), 
"ATTO_CONTR" VARCHAR2(10 CHAR), 
"RESP_CONTROLLO" VARCHAR2(10 CHAR), 
"INFRAZIONE" VARCHAR2(100 CHAR), 
"DATA_1_CONTR" VARCHAR2(20 CHAR), 
"RICH_AZ_CORR" VARCHAR2(100 CHAR), 
"AZ_CORR_ESEG" VARCHAR2(100 CHAR), 
"RICH_IMP_RIPR" VARCHAR2(100 CHAR), 
"IMP_RIPR_ESEG" VARCHAR2(100 CHAR), 
"DATA_2_CONTR" VARCHAR2(20 CHAR), 
"ESITO_2_CONTR" VARCHAR2(100 CHAR), 
"INADEMPIENZA" VARCHAR2(100 CHAR), 
"NEGLIGENZA" VARCHAR2(100 CHAR), 
"INTENZIONALITA" VARCHAR2(100 CHAR), 
"PROGR_ACCERT_INTENZ" NUMBER, 
"COD_VIOL_INTENZ_IMPEGNI" VARCHAR2(100 CHAR), 
"REITERAZIONE" VARCHAR2(100 CHAR), 
"PROGR_ACC_REITERAZ" NUMBER, 
"PORTATA" NUMBER, 
"GRAVITA" NUMBER, 
"DURATA" NUMBER, 
"PERC_RID" NUMBER, 
"AMMONIZIONE" VARCHAR2(100 CHAR), 
"NOTE" VARCHAR2(500 CHAR), 
"AUTODICH_TRATT_NON_CHIMICO" VARCHAR2(100 CHAR),
"AUTODICH_GASOLIO" VARCHAR2(100 CHAR), 
"DATA_INSERIMENTO" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
"USER_INSERIMENTO" VARCHAR2(50 CHAR), 
"DATA_MODIFICA" TIMESTAMP (6), 
"USER_MODIFICA" VARCHAR2(50 CHAR), 
"TIPO_CONTROLLO" VARCHAR2(100 CHAR),
"PORTATA_NOTE" VARCHAR2(500 CHAR),
"GRAVITA_NOTE" VARCHAR2(500 CHAR),
"DURATA_NOTE" VARCHAR2(500 CHAR),
"INTENZIONALITA_NOTE" VARCHAR2(500 CHAR),
"SEGNALAZIONE" VARCHAR2(10 CHAR),
"APPROVAZIONE" VARCHAR2(10 CHAR)
) NOLOGGING TABLESPACE OPP_ESITI_TAB;

-- INDICE PK
CREATE INDEX IDX_ESITO_COND_ATTO_PK ON OPP_ESITI_APP_ESITO_COND_ATTO (CUAA, CAMPAGNA, COD_COND, ATTO_CONTR ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;

--PK
ALTER TABLE OPP_ESITI_APP_ESITO_COND_ATTO 
    ADD CONSTRAINT APP_ESITO_COND_ATTO_PK PRIMARY KEY ( CUAA, CAMPAGNA, COD_COND, ATTO_CONTR ) USING INDEX IDX_ESITO_COND_ATTO_PK;

COMMENT ON COLUMN "OPP_ESITI_ADM"."OPP_ESITI_APP_ESITO_COND_ATTO"."AUTODICH_TRATT_NON_CHIMICO"
IS 'autodichiarazione del trattamento non chimico';

COMMENT ON TABLE "OPP_ESITI_APP_ESITO_COND_ATTO"
IS 'tabella che contiene gli esiti dei controlli di condiizonalita per singolo atto';

-- ***********************************************************************************************

CREATE TABLE "OPP_ESITI_APP_ESITO_IMPEGNI" (
"ID" NUMBER(*,0) NOT NULL ENABLE, 
"CUAA" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
"DOMANDA_OPR" VARCHAR2(15 CHAR) NOT NULL ENABLE, 
"CAMPAGNA" NUMBER(*,0), 
"INTERVENTO" VARCHAR2(10 CHAR), 
"SOTTOINTERVENTO" VARCHAR2(10 CHAR), 
"ESITO" VARCHAR2(8 CHAR), 
"PERC_RID_SOTTOINTERVENTO" VARCHAR2(10 CHAR), 
"NOTE" VARCHAR2(500 CHAR), 
"STATO" VARCHAR2(20 CHAR), 
"DATA_CONTROLLO" VARCHAR2(50 CHAR),
"REITERAZIONE" VARCHAR2(10 CHAR),
"PROGR_REITERAZIONE" VARCHAR2(10 CHAR),
"INADEMP_GRAVE" VARCHAR2(10 CHAR),
"CARICO_ALPEGGIO" VARCHAR2(50 CHAR), 
"PERC_RID_COMMISS_RIESAME" VARCHAR2(10 CHAR), 
"STATO_POST_COMMISS_RIESAME" VARCHAR2(10 CHAR), 
"DATA_COMMISS_RIESAME" VARCHAR2(50 CHAR),
"DATA_INSERIMENTO" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
"USER_INSERIMENTO" VARCHAR2(50 CHAR), 
"DATA_MODIFICA" TIMESTAMP (6), 
"USER_MODIFICA" VARCHAR2(50 CHAR), 
"ESITO_PREMIO_TRASPORTO" VARCHAR2(50 CHAR),
"PERC_RID_PREMIO_TRASPORTO" VARCHAR2(10 CHAR), 
"ESITO_RINUNCIA_INSILATO" VARCHAR2(50 CHAR),
"IMPORTO_RID_RINUNCIA_INSILATO" NUMBER(10,2),
"CONTROLLO_ESTIVO" VARCHAR2(10 CHAR),
"PERC_RID_CARICO_BESTIAME" VARCHAR2(10 CHAR),
"ESITO_TRANSFORMAZIONE_LATTE" VARCHAR2(50 CHAR),
"SEGNALAZIONE" VARCHAR2(10 CHAR)
) NOLOGGING TABLESPACE OPP_ESITI_TAB;

-- INDICI
CREATE INDEX IDX_ESITO_IMPEGNI_DOMANDA_OPR ON OPP_ESITI_APP_ESITO_IMPEGNI (DOMANDA_OPR ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;
CREATE INDEX IDX_ESITO_IMPEGNI_CUAA ON OPP_ESITI_APP_ESITO_IMPEGNI (CUAA ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;
CREATE INDEX IDX_ESITO_IMPEGNI_CAMPAGNA ON OPP_ESITI_APP_ESITO_IMPEGNI (CAMPAGNA ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;
-- INDICE PK
CREATE INDEX IDX_ESITO_IMPEGNI_PK ON OPP_ESITI_APP_ESITO_IMPEGNI (DOMANDA_OPR, INTERVENTO, SOTTOINTERVENTO ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;

--PK
ALTER TABLE OPP_ESITI_APP_ESITO_IMPEGNI 
    ADD CONSTRAINT OPP_ESITI_APP_ESITO_IMPEGNI_PK PRIMARY KEY ( DOMANDA_OPR, INTERVENTO, SOTTOINTERVENTO, CONTROLLO_ESTIVO ) USING INDEX IDX_ESITO_IMPEGNI_PK;

COMMENT ON TABLE "OPP_ESITI_APP_ESITO_IMPEGNI"
IS 'tabella che contiene gli esiti dei controlli impegni';

-- ***********************************************************************************************

CREATE TABLE "OPP_ESITI_APP_ESITO_IMP_EXT" (
"CUAA" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
"DOMANDA_OPR" VARCHAR2(15 CHAR) NOT NULL ENABLE, 
"CAMPAGNA" NUMBER, 
"INTERVENTO" VARCHAR2(10 CHAR), 
"SOTTOINTERVENTO" VARCHAR2(10 CHAR), 
"ESITO" VARCHAR2(8 CHAR), 
"IMPEGNO" VARCHAR2(100 CHAR), 
"PERC_RID" NUMBER, 
"STATO" VARCHAR2(20 CHAR), 
"ESITO_RINUNCIA_INSILATO" VARCHAR2(50 CHAR),
"IMPORTO_RID_RINUNCIA_INSILATO" NUMBER(10,2),
"ESCLUSIONE" VARCHAR2(50 CHAR),
"ESCLUSIONE_NOTE" VARCHAR2(500 CHAR),
"REITERAZIONE" VARCHAR2(100 CHAR), 
"PROGR_ACC_REITERAZ" NUMBER, 
"PORTATA" NUMBER, 
"GRAVITA" NUMBER, 
"DURATA" NUMBER,
"INADEMP_GRAVE" VARCHAR2(10 CHAR),
"SEGNALAZIONE" VARCHAR2(10 CHAR),
"APPROVAZIONE" VARCHAR2(10 CHAR),
"PORTATA_NOTE" VARCHAR2(500 CHAR),
"GRAVITA_NOTE" VARCHAR2(500 CHAR),
"DURATA_NOTE" VARCHAR2(500 CHAR),
"NUMERO_DECRETO"	VARCHAR2(50 CHAR),
"DATA_DECRETO"	DATE,
"DATA_INSERIMENTO" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
"USER_INSERIMENTO" VARCHAR2(50 CHAR), 
"DATA_MODIFICA" TIMESTAMP (6), 
"USER_MODIFICA" VARCHAR2(50 CHAR),
"NOTE" VARCHAR2(500 CHAR),
"DATA_CONTROLLO" DATE
) NOLOGGING TABLESPACE OPP_ESITI_TAB;

-- INDICI
CREATE INDEX IDX_ESITO_IMP_EXT_DOMANDA_OPR ON OPP_ESITI_APP_ESITO_IMP_EXT (DOMANDA_OPR ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;
CREATE INDEX IDX_ESITO_IMP_EXT_CUAA ON OPP_ESITI_APP_ESITO_IMP_EXT (CUAA ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;
CREATE INDEX IDX_ESITO_IMP_EXT_CAMPAGNA ON OPP_ESITI_APP_ESITO_IMP_EXT (CAMPAGNA ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;
-- INDICE PK
CREATE INDEX IDX_ESITO_IMP_EXT_PK ON OPP_ESITI_APP_ESITO_IMP_EXT (DOMANDA_OPR, INTERVENTO, SOTTOINTERVENTO ASC, IMPEGNO)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;

ALTER TABLE OPP_ESITI_APP_ESITO_IMP_EXT ADD CONSTRAINT OPP_ESITI_APP_ESITO_IMP_EXT_PK PRIMARY KEY ( DOMANDA_OPR, INTERVENTO, SOTTOINTERVENTO, IMPEGNO ) USING INDEX IDX_ESITO_IMP_EXT_PK;
    
COMMENT ON TABLE "OPP_ESITI_APP_ESITO_IMP_EXT" IS 'tabella che contiene gli esiti dei controlli impegni EXTRACAMPIONE';

-- ***********************************************************************************************

CREATE TABLE "OPP_ESITI_APP_UBA_AMM" (
"CUAA" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
"DOMANDA_OPR" VARCHAR2(15 CHAR) NOT NULL ENABLE, 
"CAMPAGNA" NUMBER(*,0), 
"INTERVENTO" VARCHAR2(10 CHAR), 
"ESITO" VARCHAR2(10 CHAR),
"STATO" VARCHAR2(50 CHAR),
"UBA_RICHIESTI" NUMBER, 
"UBA_ACCERTATI" NUMBER, 
"UBA_IRREGOLARI" NUMBER,
"PERC_RID" NUMBER(10, 2),
"NOTE" VARCHAR2(500 CHAR), 
"DATA_INSERIMENTO" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
"USER_INSERIMENTO" VARCHAR2(50 CHAR), 
"DATA_MODIFICA" TIMESTAMP (6), 
"USER_MODIFICA" VARCHAR2(50 CHAR)
) NOLOGGING TABLESPACE OPP_ESITI_TAB;

CREATE INDEX IDX_UBA_AMM_DOMANDA ON OPP_ESITI_APP_UBA_AMM (DOMANDA_OPR ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;
CREATE INDEX IDX_UBA_AMM_CUAA ON OPP_ESITI_APP_UBA_AMM (CUAA ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;
CREATE INDEX IDX_UBA_AMM_CAMPAGNA ON OPP_ESITI_APP_UBA_AMM (CAMPAGNA ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;


-- INDICE PK
CREATE INDEX IDX_UBA_AMM_PK ON OPP_ESITI_APP_UBA_AMM (DOMANDA_OPR, INTERVENTO ASC) TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;

--PK
ALTER TABLE OPP_ESITI_APP_UBA_AMM 
    ADD CONSTRAINT OPP_ESITI_APP_UBA_AMM_PK PRIMARY KEY ( DOMANDA_OPR, INTERVENTO ) USING INDEX IDX_UBA_AMM_PK;

COMMENT ON TABLE "OPP_ESITI_APP_UBA_AMM"
IS 'tabella che contiene gli esiti UBA ammissibilità';

-- ***********************************************************************************************

CREATE TABLE "OPP_ESITI_APP_ESITO_SUP" (
"ID" NUMBER NOT NULL ENABLE, 
"CUAA" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
"DOMANDA_OPR" VARCHAR2(15 CHAR) NOT NULL ENABLE, 
"DOMANDA_AGEA" VARCHAR2(15 CHAR),
"MISURA" VARCHAR2(10 CHAR),
"CAMPAGNA" NUMBER(*,0), 
"STATO_AZIONE" VARCHAR2(50 CHAR), 
"GRUPPO_COLTURA" VARCHAR2(30 CHAR), 
"INTERVENTO" VARCHAR2(10 CHAR), 
"SOTTOINTERVENTO" VARCHAR2(10 CHAR), 
"SUP_DICHIARATA" NUMBER, 
"SUP_ACCERTATA" NUMBER, 
"DIFFERENZA" NUMBER, 
"SCOST_PERC" NUMBER,
"SANZIONE_ANNULLATA" VARCHAR2(10 CHAR), 
"NOTE" VARCHAR2(500 CHAR), 
"DATA_INSERIMENTO" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
"USER_INSERIMENTO" VARCHAR2(50 CHAR), 
"DATA_MODIFICA" TIMESTAMP (6), 
"USER_MODIFICA" VARCHAR2(50 CHAR), 
"CHANGED" VARCHAR2(1 CHAR),
"CARTELLINO_GIALLO" VARCHAR2(10 CHAR),
"ESITO" VARCHAR2(20 CHAR),
"DATA_CONTROLLO" DATE,
"EFFETTO" VARCHAR2(500 CHAR)
) NOLOGGING TABLESPACE OPP_ESITI_TAB;

COMMENT ON COLUMN OPP_ESITI_ADM.OPP_ESITI_APP_ESITO_SUP.CHANGED 
IS 'Y=riga modificata tramite applicazione, N=riga inserita tramite flusso automatico';

-- INDICI
CREATE INDEX IDX_ESITO_SUP_CUAA ON OPP_ESITI_APP_ESITO_SUP (CUAA ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;
CREATE INDEX IDX_ESITO_SUP_DOMANDA_OPR ON OPP_ESITI_APP_ESITO_SUP (DOMANDA_OPR ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;
CREATE INDEX IDX_ESITO_SUP_CAMPAGNA ON OPP_ESITI_APP_ESITO_SUP (CAMPAGNA ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;
-- INDICE PK
CREATE INDEX IDX_ESITO_SUP_PK ON OPP_ESITI_APP_ESITO_SUP (DOMANDA_OPR, INTERVENTO, SOTTOINTERVENTO ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;

--PK
ALTER TABLE OPP_ESITI_APP_ESITO_SUP 
    ADD CONSTRAINT OPP_ESITI_APP_ESITO_SUP_PK PRIMARY KEY ( DOMANDA_OPR, INTERVENTO, SOTTOINTERVENTO ) USING INDEX IDX_ESITO_SUP_PK;
	
COMMENT ON TABLE "OPP_ESITI_APP_ESITO_SUP"
IS 'tabella che contiene gli esiti dei controlli a superficie';

-- ***********************************************************************************************

CREATE TABLE "OPP_ESITI_APP_ESITO_SUP_BKP" (
"ID" NUMBER NOT NULL ENABLE, 
"CUAA" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
"DOMANDA_OPR" VARCHAR2(15 CHAR) NOT NULL ENABLE, 
"DOMANDA_AGEA" VARCHAR2(15 CHAR),
"MISURA" VARCHAR2(10 CHAR),
"CAMPAGNA" NUMBER(*,0), 
"STATO_AZIONE" VARCHAR2(50 CHAR), 
"GRUPPO_COLTURA" VARCHAR2(30 CHAR), 
"INTERVENTO" VARCHAR2(5 CHAR), 
"SOTTOINTERVENTO" VARCHAR2(5 CHAR), 
"SUP_DICHIARATA" NUMBER, 
"SUP_ACCERTATA" NUMBER, 
"DIFFERENZA" NUMBER, 
"SCOST_PERC" NUMBER, 
"SANZIONE_ANNULLATA" VARCHAR2(10 CHAR), 
"NOTE" VARCHAR2(500 CHAR), 
"DATA_INSERIMENTO" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
"USER_INSERIMENTO" VARCHAR2(50 CHAR), 
"DATA_MODIFICA" TIMESTAMP (6), 
"USER_MODIFICA" VARCHAR2(50 CHAR), 
"CHANGED" VARCHAR2(1 CHAR),
"KEY_CARICAMENTO" VARCHAR2(15 CHAR),
"CARTELLINO_GIALLO" VARCHAR2(10 CHAR),
"ESITO" VARCHAR2(20 CHAR)
) NOLOGGING TABLESPACE OPP_ESITI_TAB;


-- INDICE PK
CREATE INDEX IDX_ESITO_SUP_BKP_PK ON OPP_ESITI_APP_ESITO_SUP_BKP (DOMANDA_OPR, INTERVENTO, SOTTOINTERVENTO  ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;


--PK
ALTER TABLE OPP_ESITI_APP_ESITO_SUP_BKP 
    ADD CONSTRAINT OPP_ESITI_APP_ESITO_SUP_BKP_PK PRIMARY KEY ( DOMANDA_OPR, INTERVENTO, SOTTOINTERVENTO  ) USING INDEX IDX_ESITO_SUP_BKP_PK ;

COMMENT ON TABLE "OPP_ESITI_ADM"."OPP_ESITI_APP_ESITO_SUP_BKP"  IS 'TABELLA DI BACKUP PER LE RIGHE MODIFICATE';

COMMENT ON TABLE "OPP_ESITI_APP_ESITO_SUP_BKP"
IS 'tabella che contiene gli esiti dei controlli a superficie modificati dall utente';

-- ***********************************************************************************************


CREATE TABLE "OPP_ESITI_APP_NATURA_2000" (
"CUAA" VARCHAR(20 CHAR), 
"CAMPAGNA" NUMBER(*,0),  
"A1" VARCHAR(20 CHAR), 
"A5" VARCHAR(20 CHAR),
"NOTE" VARCHAR(500 CHAR),
"DATA_INSERIMENTO" TIMESTAMP DEFAULT SYSDATE NOT NULL ENABLE,
"USER_INSERIMENTO" VARCHAR(50 CHAR),
"DATA_MODIFICA" TIMESTAMP ,
"USER_MODIFICA" VARCHAR(50 CHAR)
) NOLOGGING TABLESPACE OPP_ESITI_TAB;

-- INDICE PK
CREATE INDEX IDX_NATURA_2000_PK ON OPP_ESITI_APP_NATURA_2000 (CUAA, CAMPAGNA ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;

--PK
ALTER TABLE OPP_ESITI_APP_NATURA_2000 
   ADD CONSTRAINT OPP_ESITI_APP_NATURA_2000_PK PRIMARY KEY ( CUAA, CAMPAGNA ) USING INDEX IDX_NATURA_2000_PK;

-- ***********************************************************************************************
   
CREATE TABLE "OPP_ESITI_APP_TUTELA_ACQUE" (
"CUAA" VARCHAR2(20 CHAR), 
"CONDIZIONALITA" VARCHAR2(50 CHAR), 
"ALTITUDINE_AZIENDA" VARCHAR2(20 CHAR), 
"UBA_ACCERTATE_TA" VARCHAR2(20 CHAR), 
"CARICO_BESTIAME_MASS_TA" VARCHAR2(20 CHAR), 
"CARICO_ALPEGGIO_PSR" VARCHAR2(20 CHAR), 
"CARICO_BESTIAME_ATTUALE_TA" VARCHAR2(20 CHAR), 
"CARICO_BESTIAME_ATTUALE_PSR" VARCHAR2(20 CHAR), 
"UBA_ECCESSIVE_TA" VARCHAR2(20 CHAR), 
"TOLLERANZA_CAR_BEST_MIN_PSR" VARCHAR2(20 CHAR), 
"TOLLERANZA_CAR_BEST_MASS_PSR" VARCHAR2(20 CHAR), 
"CAPACITA_STOCCAGGI" VARCHAR2(50 CHAR), 
"STOCCAGGI_FUNZIONE_TENUTI" VARCHAR2(50 CHAR), 
"ESITO_STOCCAGGI" VARCHAR2(50 CHAR),
"SECONDO_CONTR_STOCCAGGIO" VARCHAR2(20 CHAR),
"DATA_SECONDO_CONTR_STOCCAGGIO" VARCHAR2(15 CHAR),
"PRESENTE_DICHIARAZIONI" VARCHAR2(50 CHAR), 
"ESITO_CARICO_BESTIAME_TA" VARCHAR2(50 CHAR), 
"NOTE" VARCHAR2(500 CHAR), 
"STATO" VARCHAR2(50 CHAR), 
"CAMPAGNA" NUMBER, 
"USER_INSERIMENTO" VARCHAR2(50 CHAR), 
"DATA_INSERIMENTO" DATE DEFAULT SYSDATE, 
"USER_MODIFICA" VARCHAR2(50 CHAR), 
"DATA_MODIFICA" DATE, 
UBA_ACCERTATE_PSR varchar(20 CHAR),
TOLLERANZA_CAR_BEST_MASS_TA varchar(20 CHAR),
AVG_CARICO_BESTIAME varchar(20 CHAR),
ESITO_CARICO_BESTIAME_PSR varchar(50 CHAR),
PUNTI_ALTITUDINE varchar(20 CHAR)
) NOLOGGING TABLESPACE OPP_ESITI_TAB;

-- INDICE PK
CREATE INDEX IDX_CUAA_TUT_ACQ_PK ON OPP_ESITI_APP_TUTELA_ACQUE (CUAA, CAMPAGNA)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;

--PK
ALTER TABLE OPP_ESITI_APP_TUTELA_ACQUE 
    ADD CONSTRAINT OPP_ESITI_APP_TUT_ACQ_PK PRIMARY KEY ( CUAA, CAMPAGNA) USING INDEX IDX_CUAA_TUT_ACQ_PK ;

COMMENT ON TABLE "OPP_ESITI_APP_TUTELA_ACQUE"
IS 'tabella che contiene gli esiti dei controlli sulla tutela acque';

-- ***********************************************************************************************

CREATE TABLE "OPP_ESITI_APP_UBA" (
"CUAA" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
"DOMANDA_OPR" VARCHAR2(15 CHAR) NOT NULL ENABLE, 
"CAMPAGNA" NUMBER(*,0), 
"ESITO" VARCHAR2(10 CHAR), 
"INTERVENTO" VARCHAR2(10 CHAR), 
"UBA_RICHIESTI" NUMBER, 
"UBA_ACCERTATI" NUMBER, 
"NOTE" VARCHAR2(500 CHAR), 
"DIFFERENZA" NUMBER, 
"CAPI_RICHIESTI" NUMBER, 
"CAPI_ACCERTATI" NUMBER, 
"DATA_INSERIMENTO" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
"USER_INSERIMENTO" VARCHAR2(50 CHAR), 
"DATA_MODIFICA" TIMESTAMP (6), 
"USER_MODIFICA" VARCHAR2(50 CHAR)
) NOLOGGING TABLESPACE OPP_ESITI_TAB;

CREATE INDEX IDX_UBA_DOMANDA ON OPP_ESITI_APP_UBA (DOMANDA_OPR ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;
CREATE INDEX IDX_UBA_CUAA ON OPP_ESITI_APP_UBA (CUAA ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;
CREATE INDEX IDX_UBA_CAMPAGNA ON OPP_ESITI_APP_UBA (CAMPAGNA ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;


-- INDICE PK
CREATE INDEX IDX_UBA_PK ON OPP_ESITI_APP_UBA (DOMANDA_OPR, INTERVENTO ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;

--PK
ALTER TABLE OPP_ESITI_APP_UBA 
    ADD CONSTRAINT OPP_ESITI_APP_UBA_PK PRIMARY KEY ( DOMANDA_OPR, INTERVENTO ) USING INDEX IDX_UBA_PK;

COMMENT ON TABLE "OPP_ESITI_APP_UBA"
IS 'tabella che contiene gli esiti UBA';

-- ***********************************************************************************************

CREATE TABLE "OPP_ESITI_APP_UTENTI" (
"USERNAME" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
"NOME_COMPLETO" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
"ROLE_ADMIN_USER" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
"ROLE_ADMIN_DESCRIPTION" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
"ROLE_USER" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
"ROLE_WR_IMP" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
"ROLE_WR_COND" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
"ROLE_WR_SUP" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
"ROLE_WR_ACQUE" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
"ROLE_WR_CAMP" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
"ROLE_WR_UBA" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
"USER_CREAZIONE" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
"DATA_CREAZIONE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
"USER_MODIFICA" VARCHAR2(50 CHAR), 
"DATA_MODIFICA" DATE DEFAULT NULL, 
"ROLE_WR_ZOOT" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
"ROLE_WR_RMFITFER" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
) NOLOGGING TABLESPACE OPP_ESITI_TAB;

-- INDICE PK
CREATE INDEX IDX_UTENTI_PK ON OPP_ESITI_APP_UTENTI (USERNAME ASC)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;

--PK
ALTER TABLE OPP_ESITI_APP_UTENTI 
    ADD CONSTRAINT OPP_ESITI_APP_UTENTI_PK PRIMARY KEY ( USERNAME ) USING INDEX IDX_UTENTI_PK;

COMMENT ON TABLE "OPP_ESITI_APP_UTENTI"
IS 'tabella che contiene gli utenti autorizzati ad accedere al portale con il relativo ruolo';


-- ***********************************************************************************************

CREATE TABLE "OPP_ESITI_APP_ZOOT_STATO" (
"CUAA" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
"DOMANDA" VARCHAR2(15 CHAR) NOT NULL ENABLE, 
"CAMPAGNA" NUMBER(*,0), 
"CONTR_AMM_BOVINI" VARCHAR2(50 CHAR),
"ESITO_AMM_BOVINI" VARCHAR2(50 CHAR),
"CONTR_AMM_OVICAPRINI" VARCHAR2(50 CHAR),
"ESITO_AMM_OVICAPRINI" VARCHAR2(50 CHAR),
"CONTR_COND" VARCHAR2(50 CHAR),
"DOCUMENTAZIONE_CONTROLLO" VARCHAR2(50 CHAR),
"PERSONA_PRESENTE" VARCHAR2(200 CHAR),
"PERSONA_PRESENTE_RUOLO" VARCHAR2(200 CHAR),
"PERSONA_PRESENTE_DOC" VARCHAR2(50 CHAR),
"FLG_REGISTRO_BDN" VARCHAR2(20 CHAR),
"FLG_FOTO_REGISTRO_STALLA" VARCHAR2(20 CHAR),
"FLG_ALTRO" VARCHAR2(20 CHAR),
"NOTE" VARCHAR2(200 CHAR),
"FLG_FIRMA_PRODUTTORE" VARCHAR2(20 CHAR),
"FLG_CONTROLLORE" VARCHAR2(20 CHAR),
"DATA_CONTROLLO" DATE,
"NOME_CONTROLLORE" VARCHAR2(100 CHAR),
"USER_CREAZIONE" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
"DATA_CREAZIONE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
"USER_MODIFICA" VARCHAR2(50 CHAR), 
"DATA_MODIFICA" DATE DEFAULT NULL,
"STATO_COMPILAZIONE" VARCHAR2(20 CHAR)
) NOLOGGING TABLESPACE OPP_ESITI_TAB;

-- INDICE PK
CREATE INDEX IDX_ZOOT_STATO_PK ON OPP_ESITI_APP_ZOOT_STATO (CUAA, DOMANDA, CAMPAGNA)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;

--PK
ALTER TABLE OPP_ESITI_APP_ZOOT_STATO 
    ADD CONSTRAINT OPP_ESITI_APP_ZOOT_STATO_PK PRIMARY KEY ( CUAA, DOMANDA, CAMPAGNA ) USING INDEX IDX_ZOOT_STATO_PK;

COMMENT ON TABLE "OPP_ESITI_APP_ZOOT_STATO"
IS 'tabella che contiene lo stato di inserimento degli esiti dei controlli zootecnia';


-- ***********************************************************************************************

CREATE TABLE "OPP_ESITI_APP_ZOOT_ESI_AMM_BOV" (
"CUAA" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
"DOMANDA" VARCHAR2(15 CHAR) NOT NULL ENABLE, 
"CAMPAGNA" NUMBER(*,0), 
"ESITO_CONTR_TIT_SPEC" VARCHAR2(20 CHAR),
"PERC_RID_CONTR_TIT_SPEC" VARCHAR2(20 CHAR),
"ESITO_CONTR_ART68_INT162" VARCHAR2(20 CHAR),
"PERC_RID_CONTR_ART68_INT162" VARCHAR2(20 CHAR),
"ESITO_CONTR_ART68_INT163" VARCHAR2(20 CHAR),
"PERC_RID_CONTR_ART68_INT163" VARCHAR2(20 CHAR),
"SANZ_FLG_APPL_PERC_RID" VARCHAR2(20 CHAR),
"SANZ_PERC_RID" VARCHAR2(20 CHAR),
"SANZ_FLG_APPL_PERC_RID_DOPPIA" VARCHAR2(20 CHAR),
"SANZ_PERC_RID_DOPPIA" VARCHAR2(20 CHAR),
"SANZ_FLG_ESCLUSIONE" VARCHAR2(20 CHAR),
"SANZ_PERC_RID_ESCLUSIONE" VARCHAR2(20 CHAR),
"NOTE" VARCHAR2(200 CHAR),
"USER_CREAZIONE" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
"DATA_CREAZIONE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
"USER_MODIFICA" VARCHAR2(50 CHAR), 
"DATA_MODIFICA" DATE DEFAULT NULL, 
"SANZ_FLG_ESCLUSIONE_ULTERIORE" VARCHAR2(20 CHAR),
"SANZ_FLG_APPL_PERC_RID_INT163" VARCHAR2(20 CHAR),
"SANZ_PERC_RID_INT163" VARCHAR2(20 CHAR),
"SANZ_FLG_APPL_PERC_RID_DOP_163" VARCHAR2(20 CHAR),
"SANZ_PERC_RID_DOPPIA_INT163" VARCHAR2(20 CHAR),
"SANZ_FLG_ESCL_INT163" VARCHAR2(20 CHAR),
"SANZ_PERC_RID_ESCL_INT163" VARCHAR2(20 CHAR),
"SANZ_FLG_ESCL_ULTERIORE_INT163" VARCHAR2(20 CHAR),
"FLG_AMM_CONTR_TIT_SPEC" VARCHAR2(20 CHAR),
"ESI_CONTR_310_311" VARCHAR2(20 CHAR),
"ESI_CONTR_313" VARCHAR2(20 CHAR),
"ESI_CONTR_315_316_318" VARCHAR2(20 CHAR),
"PERC_RID_310_311" VARCHAR2(20 CHAR),
"PERC_RID_313" VARCHAR2(20 CHAR),
"PERC_RID_315_316_318" VARCHAR2(20 CHAR),
"FLG_APPL_PERC_RID_310_311" VARCHAR2(20 CHAR),
"PERC_RID_ESI_310_311" VARCHAR2(20 CHAR),
"FLG_2X_PERC_RID_310_311" VARCHAR2(20 CHAR),
"PERC_RID_2X_310_311" VARCHAR2(20 CHAR),
"FLG_ESC_PAG_310_311" VARCHAR2(20 CHAR),
"PERC_RID_ESC_PAG_310_311" VARCHAR2(20 CHAR),
"FLG_ULT_ESC_PAG_310_311" VARCHAR2(20 CHAR),
"FLG_APPL_PERC_RID_313" VARCHAR2(20 CHAR),
"PERC_RID_ESI_313" VARCHAR2(20 CHAR),
"FLG_2X_PERC_RID_313" VARCHAR2(20 CHAR),
"PERC_RID_2X_313" VARCHAR2(20 CHAR),
"FLG_ESC_PAG_313" VARCHAR2(20 CHAR),
"PERC_RID_ESC_PAG_313" VARCHAR2(20 CHAR),
"FLG_ULT_ESC_PAG_313" VARCHAR2(20 CHAR),
"FLG_APPL_PERC_RID_315_316_318" VARCHAR2(20 CHAR),
"PERC_RID_ESI_315_316_318" VARCHAR2(20 CHAR),
"FLG_2X_PERC_RID_315_316_318" VARCHAR2(20 CHAR),
"PERC_RID_2X_315_316_318" VARCHAR2(20 CHAR),
"FLG_ESC_PAG_315_316_318" VARCHAR2(20 CHAR),
"PERC_RID_ESC_PAG_315_316_318" VARCHAR2(20 CHAR),
"FLG_ULT_ESC_PAG_315_316_318" VARCHAR2(20 CHAR),
"ESI_CONTR_322" VARCHAR2(20 CHAR),
"PERC_RID_322" VARCHAR2(20 CHAR),
"FLG_APPL_PERC_RID_322" VARCHAR2(20 CHAR),
"PERC_RID_ESI_322" VARCHAR2(20 CHAR),
"FLG_2X_PERC_RID_322" VARCHAR2(20 CHAR),
"PERC_RID_2X_322" VARCHAR2(20 CHAR),
"FLG_ESC_PAG_322" VARCHAR2(20 CHAR),
"PERC_RID_ESC_PAG_322" VARCHAR2(20 CHAR),
"FLG_ULT_ESC_PAG_322" VARCHAR2(20 CHAR)
) NOLOGGING TABLESPACE OPP_ESITI_TAB;

-- INDICE PK
CREATE INDEX IDX_ZOOT_ESITO_AMM_BOV_PK ON OPP_ESITI_APP_ZOOT_ESI_AMM_BOV (CUAA, DOMANDA, CAMPAGNA)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;

--PK
ALTER TABLE OPP_ESITI_APP_ZOOT_ESI_AMM_BOV 
    ADD CONSTRAINT ESITI_APP_ZOOT_ESI_AMM_BOV_PK PRIMARY KEY ( CUAA, DOMANDA, CAMPAGNA ) USING INDEX IDX_ZOOT_ESITO_AMM_BOV_PK;

COMMENT ON TABLE "OPP_ESITI_APP_ZOOT_ESI_AMM_BOV"
IS 'tabella che contiene gli esiti dei controlli zootecnia ammissibilita bovini';

-- ***********************************************************************************************

  CREATE TABLE "APP_ZOOT_ESI_AMM_BOV_INT" 
   (	"CUAA" VARCHAR2(16 CHAR), 
		"DOMANDA" VARCHAR2(20 CHAR), 
		"CAMPAGNA" NUMBER, 
		"INTERVENTO" VARCHAR2(20 CHAR), 
		"CAMPO" VARCHAR2(200 CHAR), 
		"VALORE" VARCHAR2(200 CHAR)
   ) NOLOGGING TABLESPACE "OPP_ESITI_TAB" ;
   
   -- INDICE PK
   CREATE UNIQUE INDEX "IDX_APP_ZOOT_ESI_AMM_INT_PK" ON "APP_ZOOT_ESI_AMM_BOV_INT" ("CUAA", "DOMANDA", "CAMPAGNA", "INTERVENTO", "CAMPO") ;

   --PK
   ALTER TABLE APP_ZOOT_ESI_AMM_BOV_INT 
   ADD CONSTRAINT APP_ZOOT_ESI_AMM_BOV_INT_PK PRIMARY KEY ( CUAA, DOMANDA, CAMPAGNA, INTERVENTO, CAMPO ) USING INDEX IDX_APP_ZOOT_ESI_AMM_INT_PK;
    
   COMMENT ON TABLE "APP_ZOOT_ESI_AMM_BOV_INT"
   IS 'tabella che contiene gli esiti dei controlli zootecnia ammissibilita bovini';
   
-- ***********************************************************************************************

CREATE TABLE "OPP_ESITI_APP_ZOOT_ESI_AMM_OVI" (
"CUAA" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
"DOMANDA" VARCHAR2(15 CHAR) NOT NULL ENABLE, 
"CAMPAGNA" NUMBER(*,0), 
"ESITO_CONTR_TIT_SPEC" VARCHAR2(20 CHAR),
"PERC_RID_CONTR_TIT_SPEC" VARCHAR2(20 CHAR),
"ESITO_CONTR_ART68_INT168" VARCHAR2(20 CHAR),
"PERC_RID_CONTR_ART68_INT168" VARCHAR2(20 CHAR),
"SANZ_FLG_APPL_PERC_RID" VARCHAR2(20 CHAR),
"SANZ_PERC_RID" VARCHAR2(20 CHAR),
"SANZ_FLG_APPL_PERC_RID_DOPPIA" VARCHAR2(20 CHAR),
"SANZ_PERC_RID_DOPPIA" VARCHAR2(20 CHAR),
"SANZ_FLG_ESCLUSIONE" VARCHAR2(20 CHAR),
"SANZ_PERC_RID_ESCLUSIONE" VARCHAR2(20 CHAR),
"NOTE" VARCHAR2(200 CHAR),
"USER_CREAZIONE" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
"DATA_CREAZIONE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
"USER_MODIFICA" VARCHAR2(50 CHAR), 
"DATA_MODIFICA" DATE DEFAULT NULL, 
"SANZ_FLG_ESCLUSIONE_ULTERIORE" VARCHAR2(20 CHAR),
"FLG_AMM_CONTR_TIT_SPEC" VARCHAR2(20 CHAR),
"ESI_CONTR_320" VARCHAR2(20 CHAR),
"PERC_RID_320" VARCHAR2(20 CHAR),
"FLG_APPL_PERC_RID_320" VARCHAR2(20 CHAR),
"PERC_RID_ESI_320" VARCHAR2(20 CHAR),
"FLG_2X_PERC_RID_320" VARCHAR2(20 CHAR),
"PERC_RID_2X_320" VARCHAR2(20 CHAR),
"FLG_ESC_PAG_320" VARCHAR2(20 CHAR),
"PERC_RID_ESC_PAG_320" VARCHAR2(20 CHAR),
"FLG_ULT_ESC_PAG_320" VARCHAR2(20 CHAR)
) NOLOGGING TABLESPACE OPP_ESITI_TAB;

-- INDICE PK
CREATE INDEX IDX_ZOOT_ESITO_AMM_OVI_PK ON OPP_ESITI_APP_ZOOT_ESI_AMM_OVI (CUAA, DOMANDA, CAMPAGNA)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;

--PK
ALTER TABLE OPP_ESITI_APP_ZOOT_ESI_AMM_OVI 
    ADD CONSTRAINT ESITI_APP_ZOOT_ESI_AMM_OVI_PK PRIMARY KEY ( CUAA, DOMANDA, CAMPAGNA ) USING INDEX IDX_ZOOT_ESITO_AMM_OVI_PK;

COMMENT ON TABLE "OPP_ESITI_APP_ZOOT_ESI_AMM_OVI"
IS 'tabella che contiene gli esiti dei controlli zootecnia ammissibilita ovicaprini';


-- ***********************************************************************************************

CREATE TABLE "OPP_ESITI_APP_ZOOT_CTR_AMM_BOV" (
"CUAA" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
"DOMANDA" VARCHAR2(15 CHAR) NOT NULL ENABLE, 
"CAMPAGNA" NUMBER(*,0), 
"CAPI_ANAGRAFE"  NUMBER(*,0),
"CAPI_REGISTRO"  NUMBER(*,0),
"CAPI_PRESENTI"  NUMBER(*,0),
"FLG_REGISTRO_ASSENTE" VARCHAR2(20 CHAR),
"FLG_INOSSERVANZA_NORME" VARCHAR2(20 CHAR),
"CAPI_NON_CONFORMI_TOT"  NUMBER(*,0),
"CAPI_NON_CONFORMI_TIT_SPEC"  NUMBER(*,0),
"CAPI_NON_CONFORMI_ART68_INT162"  NUMBER(*,0),
"CAPI_NON_CONFORMI_ART68_INT163"  NUMBER(*,0),
"DICHIARAZIONI_PRODUTTORE" VARCHAR2(200 CHAR),
"DICHIARAZIONI_CONTROLLORE" VARCHAR2(200 CHAR),
"FLG_ANOMALIE" VARCHAR2(20 CHAR),
"NOTE" VARCHAR2(200 CHAR),
"USER_CREAZIONE" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
"DATA_CREAZIONE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
"USER_MODIFICA" VARCHAR2(50 CHAR), 
"DATA_MODIFICA" DATE DEFAULT NULL,
"CAPI_RICHIESTI_INT_310_311" NUMBER(*,0),
"CAPI_RICHIESTI_INT_313" NUMBER(*,0),
"CAPI_RICHIESTI_INT_315_316_318" NUMBER(*,0),
"CAPI_IRREG_INT_310_311" NUMBER(*,0),
"CAPI_IRREG_INT_313" NUMBER(*,0),
"CAPI_IRREG_INT_315_316_318" NUMBER(*,0),
"CAPI_RICHIESTI_INT_322" NUMBER,
"CAPI_IRREG_INT_322" NUMBER,
"CAPI_RICHIESTI_INT_310" NUMBER(*, 0),
"CAPI_RICHIESTI_INT_311" NUMBER(*, 0),
"CAPI_RICHIESTI_INT_315" NUMBER(*, 0),
"CAPI_RICHIESTI_INT_316" NUMBER(*, 0),
"CAPI_RICHIESTI_INT_318" NUMBER(*, 0),
"CAPI_IRREG_INT_310" NUMBER(*, 0),
"CAPI_IRREG_INT_311" NUMBER(*, 0),
"CAPI_IRREG_INT_315" NUMBER(*, 0),
"CAPI_IRREG_INT_316" NUMBER(*, 0),
"CAPI_IRREG_INT_318" NUMBER(*, 0),
"CAPI_ANOM_AMM_SCARICO_BDN" VARCHAR2(10 CHAR)
) NOLOGGING TABLESPACE OPP_ESITI_TAB;

-- INDICE PK
CREATE INDEX IDX_ZOOT_CTR_AMM_BOV_PK ON OPP_ESITI_APP_ZOOT_CTR_AMM_BOV (CUAA, DOMANDA, CAMPAGNA)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;

--PK
ALTER TABLE OPP_ESITI_APP_ZOOT_CTR_AMM_BOV 
    ADD CONSTRAINT ESITI_APP_ZOOT_CTR_AMM_BOV_PK PRIMARY KEY ( CUAA, DOMANDA, CAMPAGNA ) USING INDEX IDX_ZOOT_CTR_AMM_BOV_PK;

COMMENT ON TABLE "OPP_ESITI_APP_ZOOT_CTR_AMM_BOV"
IS 'tabella che contiene i dati dei controlli zootecnia ammissibilita bovini';


-- ***********************************************************************************************

CREATE TABLE "OPP_ESITI_APP_ZOOT_CTR_AMM_OVI" (
"CUAA" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
"DOMANDA" VARCHAR2(15 CHAR) NOT NULL ENABLE, 
"CAMPAGNA" NUMBER(*,0), 
"CAPI_ANAGRAFE_TOT" NUMBER(*,0),
"CAPI_ANAGRAFE_M" NUMBER(*,0),
"CAPI_ANAGRAFE_F" NUMBER(*,0),
"CAPI_REGISTRO_TOT" NUMBER(*,0),
"CAPI_REGISTRO_M" NUMBER(*,0),
"CAPI_REGISTRO_F" NUMBER(*,0),
"CAPI_AZIENDA_TOT" NUMBER(*,0),
"CAPI_AZIENDA_M" NUMBER(*,0),
"CAPI_AZIENDA_F" NUMBER(*,0),
"FLG_INOSSERVANZA_NORME" VARCHAR2(20 CHAR),
"CAPI_NON_CONFORMI_TOT" NUMBER(*,0),
"CAPI_NON_CONFORMI_M" NUMBER(*,0),
"CAPI_NON_CONFORMI_PECORE_CAPRE" NUMBER(*,0),
"FLG_ANOMALIE" VARCHAR2(20 CHAR),
"FLG_REG_AZI_ASS_NON_COMP" VARCHAR2(20 CHAR),
"FLG_REG_AZI_NON_COMP_SIT_SOD" VARCHAR2(20 CHAR),
"FLG_REG_AZI_COMP" VARCHAR2(20 CHAR),
"DICHIARAZIONI_PRODUTTORE" VARCHAR2(200 CHAR),
"DICHIARAZIONI_CONTROLLORE" VARCHAR2(200 CHAR),
"NOTE" VARCHAR2(200 CHAR),
"USER_CREAZIONE" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
"DATA_CREAZIONE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
"USER_MODIFICA" VARCHAR2(50 CHAR), 
"DATA_MODIFICA" DATE DEFAULT NULL,
"CAPI_ANOM_AMM_SCARICO_BDN" VARCHAR2(10 CHAR)
) NOLOGGING TABLESPACE OPP_ESITI_TAB;

-- INDICE PK
CREATE INDEX IDX_ZOOT_CTR_AMM_OVI_PK ON OPP_ESITI_APP_ZOOT_CTR_AMM_OVI (CUAA, DOMANDA, CAMPAGNA)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;

--PK
ALTER TABLE OPP_ESITI_APP_ZOOT_CTR_AMM_OVI
    ADD CONSTRAINT ESITI_APP_ZOOT_CTR_AMM_OVI_PK PRIMARY KEY ( CUAA, DOMANDA, CAMPAGNA ) USING INDEX IDX_ZOOT_CTR_AMM_OVI_PK;

COMMENT ON TABLE "OPP_ESITI_APP_ZOOT_CTR_AMM_OVI"
IS 'tabella che contiene i dati dei controlli zootecnia ammissibilita ovicaprini';


-- ***********************************************************************************************

CREATE TABLE "OPP_ESITI_APP_ZOOT_CTR_COND" (
"CUAA" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
"DOMANDA" VARCHAR2(15 CHAR) NOT NULL ENABLE, 
"CAMPAGNA" NUMBER(*,0), 
"FLG_AZI_NON_REG_BDN" VARCHAR2(20 CHAR),
"FLG_REG_AZI_ASS" VARCHAR2(20 CHAR),
"FLG_REG_AZI_NON_CONFORME" VARCHAR2(20 CHAR),
"FLG_OVI_SUI_NO_MARC_DOC" VARCHAR2(20 CHAR),
"FLG_BOV_BUF_OVI_NO_REG" VARCHAR2(20 CHAR),
"FLG_BOV_BUF_OVI_IDENT_NO_CONF" VARCHAR2(20 CHAR),
"FLG_OVI_SUI_MARC_NO_CONF" VARCHAR2(20 CHAR),
"FLG_BOV_BUF_NO_PASS_MARCHI_DOC" VARCHAR2(20 CHAR),
"FLG_ANOMALIE" VARCHAR2(20 CHAR),
"CAPI_ANOMALI_BOVINI" NUMBER(*,0),
"CAPI_ANOMALI_SUINI" NUMBER(*,0),
"CAPI_ANOMALI_OVINI" NUMBER(*,0),
"CAPI_CONSISTENZA_BOVINI" NUMBER(*,0),
"CAPI_CONSISTENZA_SUINI" NUMBER(*,0),
"CAPI_CONSISTENZA_OVINI" NUMBER(*,0),
"CAPI_CONTROLLATI_BOVINI" NUMBER(*,0),
"CAPI_CONTROLLATI_SUINI" NUMBER(*,0),
"CAPI_CONTROLLATI_OVINI" NUMBER(*,0),
"NOTE" VARCHAR2(200 CHAR),
"USER_CREAZIONE" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
"DATA_CREAZIONE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
"USER_MODIFICA" VARCHAR2(50 CHAR), 
"DATA_MODIFICA" DATE DEFAULT NULL
) NOLOGGING TABLESPACE OPP_ESITI_TAB;

-- INDICE PK
CREATE INDEX IDX_ZOOT_CTR_COND_PK ON OPP_ESITI_APP_ZOOT_CTR_COND (CUAA, DOMANDA, CAMPAGNA)  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;

--PK
ALTER TABLE OPP_ESITI_APP_ZOOT_CTR_COND
    ADD CONSTRAINT ESITI_APP_ZOOT_CTR_COND_PK PRIMARY KEY ( CUAA, DOMANDA, CAMPAGNA ) USING INDEX IDX_ZOOT_CTR_COND_PK;

COMMENT ON TABLE "OPP_ESITI_APP_ZOOT_CTR_COND"
IS 'tabella che contiene i dati dei controlli zootecnia condizionalita';


-- ***********************************************************************************************

CREATE TABLE "OPP_ESITI_APP_ESITO_RM_FIT_FER" ( 
 "CUAA" VARCHAR2(20 CHAR), 
 "DOMANDA_OPR" VARCHAR2(15 CHAR), 
 "CAMPAGNA" NUMBER(38,0), 
 "MISURA" VARCHAR2(10 CHAR), 
 "ESITO_OPPAB" VARCHAR2(8 CHAR), 
 "STATO" VARCHAR2(16 CHAR), 
 "PERC_RID_FIT" VARCHAR2(10 CHAR), 
 "PERC_RID_FER" VARCHAR2(10 CHAR), 
  "PERC_TOTALE_OPPAB" VARCHAR2(10 CHAR), 
  "PERC_COMMISS_RIESAME" VARCHAR2(10 CHAR), 
 "STATO_POST_COMMISS_RIESAME" VARCHAR2(16 CHAR), 
  "DATA_COMMISS_RIESAME" VARCHAR2(50 CHAR),
  "NOTE" VARCHAR2(500 CHAR),
 "DATA_INSERIMENTO" TIMESTAMP (6) DEFAULT SYSDATE, 
 "USER_INSERIMENTO" VARCHAR2(50 CHAR), 
 "DATA_MODIFICA" TIMESTAMP (6), 
 "USER_MODIFICA" VARCHAR2(50 CHAR),
 "DATA_CONTR" DATE,
 "INTENZIONALITA" VARCHAR2(100 CHAR), 
 "PROGR_ACCERT_INTENZ" NUMBER, 
 "REITERAZIONE" VARCHAR2(100 CHAR), 
 "PROGR_ACC_REITERAZ" NUMBER, 
 "PORTATA" NUMBER, 
 "GRAVITA" NUMBER, 
 "DURATA" NUMBER,
 "SEGNALAZIONE" VARCHAR2(10 CHAR),
 "PORTATA_NOTE" VARCHAR2(500 CHAR),
 "GRAVITA_NOTE" VARCHAR2(500 CHAR),
 "DURATA_NOTE" VARCHAR2(500 CHAR),
 "INTENZIONALITA_NOTE" VARCHAR2(500 CHAR),
 "ESCLUSIONE"	VARCHAR2(100 CHAR),
 "PROGR_ACCERT_ESCLUSIONE"	NUMBER,
 "ESCLUSIONE_NOTE"	VARCHAR2(500 CHAR)
   ) ; 

   COMMENT ON TABLE "OPP_ESITI_APP_ESITO_RM_FIT_FER"  IS 'tabella che contiene gli esiti dei controlli impegni RM-FIT e FER';
   
   CREATE INDEX "IDX_ESITO_RM_FIT_FER_PK" ON "OPP_ESITI_APP_ESITO_RM_FIT_FER" ("DOMANDA_OPR", "MISURA")  TABLESPACE "OPP_ESITI_IDX" NOLOGGING ;
   
   --PK
ALTER TABLE OPP_ESITI_APP_ESITO_RM_FIT_FER
    ADD CONSTRAINT ESITI_APP_ESI_RM_FIT_FER_PK PRIMARY KEY ( DOMANDA_OPR, MISURA) USING INDEX IDX_ESITO_RM_FIT_FER_PK;


-- ***********************************************************************************************


  CREATE TABLE "OPP_ESITI_ADM"."OPP_ESITI_APP_ESITO_FITFER_EXT" 
   (	"CUAA" VARCHAR2(20 CHAR), 
	"DOMANDA_OPR" VARCHAR2(15 CHAR), 
	"CAMPAGNA" NUMBER(38,0), 
	"MISURA" VARCHAR2(10 CHAR), 
	"ESITO_OPPAB" VARCHAR2(8 CHAR), 
	"STATO" VARCHAR2(16 CHAR), 
	"PERC_RID_FIT" VARCHAR2(10 CHAR), 
	"PERC_RID_FER" VARCHAR2(10 CHAR), 
	"PERC_TOTALE_OPPAB" VARCHAR2(10 CHAR), 
	"NOTE" VARCHAR2(500 CHAR), 
	"DATA_INSERIMENTO" TIMESTAMP (6) DEFAULT SYSDATE, 
	"USER_INSERIMENTO" VARCHAR2(50 CHAR), 
	"DATA_MODIFICA" TIMESTAMP (6), 
	"USER_MODIFICA" VARCHAR2(50 CHAR), 
	"DATA_CONTR" DATE, 
	"NEGLIGENZA" VARCHAR2(100 CHAR), 
	"ESCLUSIONE" VARCHAR2(100 CHAR), 
	"PROGR_ACCERT_ESCLUSIONE" NUMBER, 
	"REITERAZIONE" VARCHAR2(100 CHAR), 
	"PROGR_ACC_REITERAZ" NUMBER, 
	"PORTATA" NUMBER, 
	"GRAVITA" NUMBER, 
	"DURATA" NUMBER, 
	"DURATA" NUMBER, 
	"INADEMP_GRAVE" VARCHAR2(10 CHAR), 
	"APPROVAZIONE" VARCHAR2(10 CHAR), 
	"PORTATA_NOTE" VARCHAR2(500 CHAR), 
	"GRAVITA_NOTE" VARCHAR2(500 CHAR), 
	"DURATA_NOTE" VARCHAR2(500 CHAR), 
	"ESCLUSIONE_NOTE" VARCHAR2(500 CHAR), 
	"NUMERO_DECRETO" VARCHAR2(50 CHAR), 
	"DATA_DECRETO" DATE
   );

   COMMENT ON TABLE "OPP_ESITI_ADM"."OPP_ESITI_APP_ESITO_FITFER_EXT"  IS 'tabella che contiene gli esiti dei controlli impegni RM-FIT e FER EXTRACAMPIONE';
   CREATE INDEX "OPP_ESITI_ADM"."IDX_ESITO_RM_FIT_FER_EXT_PK" ON "OPP_ESITI_ADM"."OPP_ESITI_APP_ESITO_FITFER_EXT" ("DOMANDA_OPR", "MISURA");
  ALTER TABLE "OPP_ESITI_ADM"."OPP_ESITI_APP_ESITO_FITFER_EXT" ADD CONSTRAINT "ESITI_APP_ESITO_FITFER_EXT_PK" PRIMARY KEY ("DOMANDA_OPR", "MISURA");
  

-- ***********************************************************************************************
--          GESTIONE RUOLI E GRANT
-- ***********************************************************************************************

-- Creazione ruolo
--create role OPP_ESITI_RL_USER;

-- assegno i grant sulle tabelle all'utente OPP_ESITI_FROM_VALAR_DEV per ALIen

grant select on OPP_ESITI_APP_ANAGRAFICHE to OPP_ESITI_FROM_VALAR_DEV;
grant insert on OPP_ESITI_APP_ANAGRAFICHE to OPP_ESITI_FROM_VALAR_DEV;
grant update on OPP_ESITI_APP_ANAGRAFICHE to OPP_ESITI_FROM_VALAR_DEV;
grant delete on OPP_ESITI_APP_ANAGRAFICHE to OPP_ESITI_FROM_VALAR_DEV;

grant select on OPP_ESITI_APP_AZIENDA to OPP_ESITI_FROM_VALAR_DEV;
--grant insert on OPP_ESITI_APP_AZIENDA to OPP_ESITI_FROM_VALAR_DEV;
--grant update on OPP_ESITI_APP_AZIENDA to OPP_ESITI_FROM_VALAR_DEV;
--grant delete on OPP_ESITI_APP_AZIENDA to OPP_ESITI_FROM_VALAR_DEV;

grant select on OPP_ESITI_APP_CAMPIONE to OPP_ESITI_FROM_VALAR_DEV;
grant insert on OPP_ESITI_APP_CAMPIONE to OPP_ESITI_FROM_VALAR_DEV;
grant update on OPP_ESITI_APP_CAMPIONE to OPP_ESITI_FROM_VALAR_DEV;
grant delete on OPP_ESITI_APP_CAMPIONE to OPP_ESITI_FROM_VALAR_DEV;

grant select on OPP_ESITI_APP_CAPI_ALLEVATI to OPP_ESITI_FROM_VALAR_DEV;
grant insert on OPP_ESITI_APP_CAPI_ALLEVATI to OPP_ESITI_FROM_VALAR_DEV;
grant update on OPP_ESITI_APP_CAPI_ALLEVATI to OPP_ESITI_FROM_VALAR_DEV;
grant delete on OPP_ESITI_APP_CAPI_ALLEVATI to OPP_ESITI_FROM_VALAR_DEV;

grant select on OPP_ESITI_APP_CODICI_COND to OPP_ESITI_FROM_VALAR_DEV;
grant insert on OPP_ESITI_APP_CODICI_COND to OPP_ESITI_FROM_VALAR_DEV;
grant update on OPP_ESITI_APP_CODICI_COND to OPP_ESITI_FROM_VALAR_DEV;
grant delete on OPP_ESITI_APP_CODICI_COND to OPP_ESITI_FROM_VALAR_DEV;

grant select on OPP_ESITI_APP_CONTROLLO to OPP_ESITI_FROM_VALAR_DEV;
grant insert on OPP_ESITI_APP_CONTROLLO to OPP_ESITI_FROM_VALAR_DEV;
grant update on OPP_ESITI_APP_CONTROLLO to OPP_ESITI_FROM_VALAR_DEV;
grant delete on OPP_ESITI_APP_CONTROLLO to OPP_ESITI_FROM_VALAR_DEV;

grant select on OPP_ESITI_APP_DOMANDA to OPP_ESITI_FROM_VALAR_DEV;
grant insert on OPP_ESITI_APP_DOMANDA to OPP_ESITI_FROM_VALAR_DEV;
grant update on OPP_ESITI_APP_DOMANDA to OPP_ESITI_FROM_VALAR_DEV;
grant delete on OPP_ESITI_APP_DOMANDA to OPP_ESITI_FROM_VALAR_DEV;

grant select on OPP_ESITI_APP_ESITO_COND to OPP_ESITI_FROM_VALAR_DEV;
grant insert on OPP_ESITI_APP_ESITO_COND to OPP_ESITI_FROM_VALAR_DEV;
grant update on OPP_ESITI_APP_ESITO_COND to OPP_ESITI_FROM_VALAR_DEV;
grant delete on OPP_ESITI_APP_ESITO_COND to OPP_ESITI_FROM_VALAR_DEV;

grant select on OPP_ESITI_APP_ESITO_COND_ATTO to OPP_ESITI_FROM_VALAR_DEV;
grant insert on OPP_ESITI_APP_ESITO_COND_ATTO to OPP_ESITI_FROM_VALAR_DEV;
grant update on OPP_ESITI_APP_ESITO_COND_ATTO to OPP_ESITI_FROM_VALAR_DEV;
grant delete on OPP_ESITI_APP_ESITO_COND_ATTO to OPP_ESITI_FROM_VALAR_DEV;

grant select on OPP_ESITI_APP_ESITO_IMPEGNI to OPP_ESITI_FROM_VALAR_DEV;
grant insert on OPP_ESITI_APP_ESITO_IMPEGNI to OPP_ESITI_FROM_VALAR_DEV;
grant update on OPP_ESITI_APP_ESITO_IMPEGNI to OPP_ESITI_FROM_VALAR_DEV;
grant delete on OPP_ESITI_APP_ESITO_IMPEGNI to OPP_ESITI_FROM_VALAR_DEV;

grant select on OPP_ESITI_APP_ESITO_SUP to OPP_ESITI_FROM_VALAR_DEV;
grant insert on OPP_ESITI_APP_ESITO_SUP to OPP_ESITI_FROM_VALAR_DEV;
grant update on OPP_ESITI_APP_ESITO_SUP to OPP_ESITI_FROM_VALAR_DEV;
grant delete on OPP_ESITI_APP_ESITO_SUP to OPP_ESITI_FROM_VALAR_DEV;

grant select on OPP_ESITI_APP_NATURA_2000 to OPP_ESITI_FROM_VALAR_DEV;
grant insert on OPP_ESITI_APP_NATURA_2000 to OPP_ESITI_FROM_VALAR_DEV;
grant update on OPP_ESITI_APP_NATURA_2000 to OPP_ESITI_FROM_VALAR_DEV;
grant delete on OPP_ESITI_APP_NATURA_2000 to OPP_ESITI_FROM_VALAR_DEV;

grant select on OPP_ESITI_APP_TUTELA_ACQUE to OPP_ESITI_FROM_VALAR_DEV;
grant insert on OPP_ESITI_APP_TUTELA_ACQUE to OPP_ESITI_FROM_VALAR_DEV;
grant update on OPP_ESITI_APP_TUTELA_ACQUE to OPP_ESITI_FROM_VALAR_DEV;
grant delete on OPP_ESITI_APP_TUTELA_ACQUE to OPP_ESITI_FROM_VALAR_DEV;

grant select on OPP_ESITI_APP_UBA to OPP_ESITI_FROM_VALAR_DEV;
grant insert on OPP_ESITI_APP_UBA to OPP_ESITI_FROM_VALAR_DEV;
grant update on OPP_ESITI_APP_UBA to OPP_ESITI_FROM_VALAR_DEV;
grant delete on OPP_ESITI_APP_UBA to OPP_ESITI_FROM_VALAR_DEV;

grant select on OPP_ESITI_APP_UBA_AMM to OPP_ESITI_FROM_VALAR_DEV;
grant insert on OPP_ESITI_APP_UBA_AMM to OPP_ESITI_FROM_VALAR_DEV;
grant update on OPP_ESITI_APP_UBA_AMM to OPP_ESITI_FROM_VALAR_DEV;
grant delete on OPP_ESITI_APP_UBA_AMM to OPP_ESITI_FROM_VALAR_DEV;

grant select on OPP_ESITI_APP_UTENTI to OPP_ESITI_FROM_VALAR_DEV;
grant insert on OPP_ESITI_APP_UTENTI to OPP_ESITI_FROM_VALAR_DEV;
grant update on OPP_ESITI_APP_UTENTI to OPP_ESITI_FROM_VALAR_DEV;
grant delete on OPP_ESITI_APP_UTENTI to OPP_ESITI_FROM_VALAR_DEV;

grant select on OPP_ESITI_DWH_INT_SOTTOINT to OPP_ESITI_FROM_VALAR_DEV;

grant select on OPP_ESITI_DWH_MATR_AMM_IDEALE to OPP_ESITI_FROM_VALAR_DEV;

grant select on OPP_ESITI_APP_ZOOT_STATO to OPP_ESITI_FROM_VALAR_DEV;
grant insert on OPP_ESITI_APP_ZOOT_STATO to OPP_ESITI_FROM_VALAR_DEV;
grant update on OPP_ESITI_APP_ZOOT_STATO to OPP_ESITI_FROM_VALAR_DEV;
grant delete on OPP_ESITI_APP_ZOOT_STATO to OPP_ESITI_FROM_VALAR_DEV;

grant select on OPP_ESITI_APP_ZOOT_ESI_AMM_BOV to OPP_ESITI_FROM_VALAR_DEV;
grant insert on OPP_ESITI_APP_ZOOT_ESI_AMM_BOV to OPP_ESITI_FROM_VALAR_DEV;
grant update on OPP_ESITI_APP_ZOOT_ESI_AMM_BOV to OPP_ESITI_FROM_VALAR_DEV;
grant delete on OPP_ESITI_APP_ZOOT_ESI_AMM_BOV to OPP_ESITI_FROM_VALAR_DEV;

grant select on OPP_ESITI_APP_ZOOT_ESI_AMM_OVI to OPP_ESITI_FROM_VALAR_DEV;
grant insert on OPP_ESITI_APP_ZOOT_ESI_AMM_OVI to OPP_ESITI_FROM_VALAR_DEV;
grant update on OPP_ESITI_APP_ZOOT_ESI_AMM_OVI to OPP_ESITI_FROM_VALAR_DEV;
grant delete on OPP_ESITI_APP_ZOOT_ESI_AMM_OVI to OPP_ESITI_FROM_VALAR_DEV;

grant select on OPP_ESITI_APP_ZOOT_CTR_AMM_BOV to OPP_ESITI_FROM_VALAR_DEV;
grant insert on OPP_ESITI_APP_ZOOT_CTR_AMM_BOV to OPP_ESITI_FROM_VALAR_DEV;
grant update on OPP_ESITI_APP_ZOOT_CTR_AMM_BOV to OPP_ESITI_FROM_VALAR_DEV;
grant delete on OPP_ESITI_APP_ZOOT_CTR_AMM_BOV to OPP_ESITI_FROM_VALAR_DEV;

grant select on OPP_ESITI_APP_ZOOT_CTR_AMM_OVI to OPP_ESITI_FROM_VALAR_DEV;
grant insert on OPP_ESITI_APP_ZOOT_CTR_AMM_OVI to OPP_ESITI_FROM_VALAR_DEV;
grant update on OPP_ESITI_APP_ZOOT_CTR_AMM_OVI to OPP_ESITI_FROM_VALAR_DEV;
grant delete on OPP_ESITI_APP_ZOOT_CTR_AMM_OVI to OPP_ESITI_FROM_VALAR_DEV;

grant select on OPP_ESITI_APP_ZOOT_CTR_COND to OPP_ESITI_FROM_VALAR_DEV;
grant insert on OPP_ESITI_APP_ZOOT_CTR_COND to OPP_ESITI_FROM_VALAR_DEV;
grant update on OPP_ESITI_APP_ZOOT_CTR_COND to OPP_ESITI_FROM_VALAR_DEV;
grant delete on OPP_ESITI_APP_ZOOT_CTR_COND to OPP_ESITI_FROM_VALAR_DEV;

grant select on OPP_ESITI_APP_ESITO_RM_FIT_FER to OPP_ESITI_FROM_VALAR_DEV;
grant insert on OPP_ESITI_APP_ESITO_RM_FIT_FER to OPP_ESITI_FROM_VALAR_DEV;
grant update on OPP_ESITI_APP_ESITO_RM_FIT_FER to OPP_ESITI_FROM_VALAR_DEV;
grant delete on OPP_ESITI_APP_ESITO_RM_FIT_FER to OPP_ESITI_FROM_VALAR_DEV;

grant select on OPP_ESITI_APP_ESITO_FITFER_EXT to OPP_ESITI_FROM_VALAR_DEV;
grant insert on OPP_ESITI_APP_ESITO_FITFER_EXT to OPP_ESITI_FROM_VALAR_DEV;
grant update on OPP_ESITI_APP_ESITO_FITFER_EXT to OPP_ESITI_FROM_VALAR_DEV;
grant delete on OPP_ESITI_APP_ESITO_FITFER_EXT to OPP_ESITI_FROM_VALAR_DEV;

grant select on OPP_ESITI_APP_ESITO_IMP_EXT to OPP_ESITI_FROM_VALAR_DEV;
grant insert on OPP_ESITI_APP_ESITO_IMP_EXT to OPP_ESITI_FROM_VALAR_DEV;
grant update on OPP_ESITI_APP_ESITO_IMP_EXT to OPP_ESITI_FROM_VALAR_DEV;
grant delete on OPP_ESITI_APP_ESITO_IMP_EXT to OPP_ESITI_FROM_VALAR_DEV;

-- assegno i grant sulle tabelle all'utente OPP_ESITI_FROM_VALAR per europa

grant select on OPP_ESITI_APP_ANAGRAFICHE to OPP_ESITI_FROM_VALAR;
grant insert on OPP_ESITI_APP_ANAGRAFICHE to OPP_ESITI_FROM_VALAR;
grant update on OPP_ESITI_APP_ANAGRAFICHE to OPP_ESITI_FROM_VALAR;
grant delete on OPP_ESITI_APP_ANAGRAFICHE to OPP_ESITI_FROM_VALAR;

grant select on OPP_ESITI_APP_AZIENDA to OPP_ESITI_FROM_VALAR;
--grant insert on OPP_ESITI_APP_AZIENDA to OPP_ESITI_FROM_VALAR;
--grant update on OPP_ESITI_APP_AZIENDA to OPP_ESITI_FROM_VALAR;
--grant delete on OPP_ESITI_APP_AZIENDA to OPP_ESITI_FROM_VALAR;

grant select on OPP_ESITI_APP_CAMPIONE to OPP_ESITI_FROM_VALAR;
grant insert on OPP_ESITI_APP_CAMPIONE to OPP_ESITI_FROM_VALAR;
grant update on OPP_ESITI_APP_CAMPIONE to OPP_ESITI_FROM_VALAR;
grant delete on OPP_ESITI_APP_CAMPIONE to OPP_ESITI_FROM_VALAR;

grant select on OPP_ESITI_APP_CAPI_ALLEVATI to OPP_ESITI_FROM_VALAR;
grant insert on OPP_ESITI_APP_CAPI_ALLEVATI to OPP_ESITI_FROM_VALAR;
grant update on OPP_ESITI_APP_CAPI_ALLEVATI to OPP_ESITI_FROM_VALAR;
grant delete on OPP_ESITI_APP_CAPI_ALLEVATI to OPP_ESITI_FROM_VALAR;

grant select on OPP_ESITI_APP_CODICI_COND to OPP_ESITI_FROM_VALAR;
grant insert on OPP_ESITI_APP_CODICI_COND to OPP_ESITI_FROM_VALAR;
grant update on OPP_ESITI_APP_CODICI_COND to OPP_ESITI_FROM_VALAR;
grant delete on OPP_ESITI_APP_CODICI_COND to OPP_ESITI_FROM_VALAR;

grant select on OPP_ESITI_APP_CONTROLLO to OPP_ESITI_FROM_VALAR;
grant insert on OPP_ESITI_APP_CONTROLLO to OPP_ESITI_FROM_VALAR;
grant update on OPP_ESITI_APP_CONTROLLO to OPP_ESITI_FROM_VALAR;
grant delete on OPP_ESITI_APP_CONTROLLO to OPP_ESITI_FROM_VALAR;

grant select on OPP_ESITI_APP_DOMANDA to OPP_ESITI_FROM_VALAR;
grant insert on OPP_ESITI_APP_DOMANDA to OPP_ESITI_FROM_VALAR;
grant update on OPP_ESITI_APP_DOMANDA to OPP_ESITI_FROM_VALAR;
grant delete on OPP_ESITI_APP_DOMANDA to OPP_ESITI_FROM_VALAR;

grant select on OPP_ESITI_APP_ESITO_COND to OPP_ESITI_FROM_VALAR;
grant insert on OPP_ESITI_APP_ESITO_COND to OPP_ESITI_FROM_VALAR;
grant update on OPP_ESITI_APP_ESITO_COND to OPP_ESITI_FROM_VALAR;
grant delete on OPP_ESITI_APP_ESITO_COND to OPP_ESITI_FROM_VALAR;

grant select on OPP_ESITI_APP_ESITO_COND_ATTO to OPP_ESITI_FROM_VALAR;
grant insert on OPP_ESITI_APP_ESITO_COND_ATTO to OPP_ESITI_FROM_VALAR;
grant update on OPP_ESITI_APP_ESITO_COND_ATTO to OPP_ESITI_FROM_VALAR;
grant delete on OPP_ESITI_APP_ESITO_COND_ATTO to OPP_ESITI_FROM_VALAR;

grant select on OPP_ESITI_APP_ESITO_IMPEGNI to OPP_ESITI_FROM_VALAR;
grant insert on OPP_ESITI_APP_ESITO_IMPEGNI to OPP_ESITI_FROM_VALAR;
grant update on OPP_ESITI_APP_ESITO_IMPEGNI to OPP_ESITI_FROM_VALAR;
grant delete on OPP_ESITI_APP_ESITO_IMPEGNI to OPP_ESITI_FROM_VALAR;

grant select on OPP_ESITI_APP_ESITO_SUP to OPP_ESITI_FROM_VALAR;
grant insert on OPP_ESITI_APP_ESITO_SUP to OPP_ESITI_FROM_VALAR;
grant update on OPP_ESITI_APP_ESITO_SUP to OPP_ESITI_FROM_VALAR;
grant delete on OPP_ESITI_APP_ESITO_SUP to OPP_ESITI_FROM_VALAR;

grant select on OPP_ESITI_APP_NATURA_2000 to OPP_ESITI_FROM_VALAR;
grant insert on OPP_ESITI_APP_NATURA_2000 to OPP_ESITI_FROM_VALAR;
grant update on OPP_ESITI_APP_NATURA_2000 to OPP_ESITI_FROM_VALAR;
grant delete on OPP_ESITI_APP_NATURA_2000 to OPP_ESITI_FROM_VALAR;

grant select on OPP_ESITI_APP_TUTELA_ACQUE to OPP_ESITI_FROM_VALAR;
grant insert on OPP_ESITI_APP_TUTELA_ACQUE to OPP_ESITI_FROM_VALAR;
grant update on OPP_ESITI_APP_TUTELA_ACQUE to OPP_ESITI_FROM_VALAR;
grant delete on OPP_ESITI_APP_TUTELA_ACQUE to OPP_ESITI_FROM_VALAR;

grant select on OPP_ESITI_APP_UBA to OPP_ESITI_FROM_VALAR;
grant insert on OPP_ESITI_APP_UBA to OPP_ESITI_FROM_VALAR;
grant update on OPP_ESITI_APP_UBA to OPP_ESITI_FROM_VALAR;
grant delete on OPP_ESITI_APP_UBA to OPP_ESITI_FROM_VALAR;

grant select on OPP_ESITI_APP_UBA_AMM to OPP_ESITI_FROM_VALAR;
grant insert on OPP_ESITI_APP_UBA_AMM to OPP_ESITI_FROM_VALAR;
grant update on OPP_ESITI_APP_UBA_AMM to OPP_ESITI_FROM_VALAR;
grant delete on OPP_ESITI_APP_UBA_AMM to OPP_ESITI_FROM_VALAR;

grant select on OPP_ESITI_APP_UTENTI to OPP_ESITI_FROM_VALAR;
grant insert on OPP_ESITI_APP_UTENTI to OPP_ESITI_FROM_VALAR;
grant update on OPP_ESITI_APP_UTENTI to OPP_ESITI_FROM_VALAR;
grant delete on OPP_ESITI_APP_UTENTI to OPP_ESITI_FROM_VALAR;

grant select on OPP_ESITI_DWH_INT_SOTTOINT to OPP_ESITI_FROM_VALAR;

grant select on OPP_ESITI_DWH_MATR_AMM_IDEALE to OPP_ESITI_FROM_VALAR;

grant select on OPP_ESITI_APP_ZOOT_STATO to OPP_ESITI_FROM_VALAR;
grant insert on OPP_ESITI_APP_ZOOT_STATO to OPP_ESITI_FROM_VALAR;
grant update on OPP_ESITI_APP_ZOOT_STATO to OPP_ESITI_FROM_VALAR;
grant delete on OPP_ESITI_APP_ZOOT_STATO to OPP_ESITI_FROM_VALAR;

grant select on OPP_ESITI_APP_ZOOT_ESI_AMM_BOV to OPP_ESITI_FROM_VALAR;
grant insert on OPP_ESITI_APP_ZOOT_ESI_AMM_BOV to OPP_ESITI_FROM_VALAR;
grant update on OPP_ESITI_APP_ZOOT_ESI_AMM_BOV to OPP_ESITI_FROM_VALAR;
grant delete on OPP_ESITI_APP_ZOOT_ESI_AMM_BOV to OPP_ESITI_FROM_VALAR;

grant select on OPP_ESITI_APP_ZOOT_ESI_AMM_OVI to OPP_ESITI_FROM_VALAR;
grant insert on OPP_ESITI_APP_ZOOT_ESI_AMM_OVI to OPP_ESITI_FROM_VALAR;
grant update on OPP_ESITI_APP_ZOOT_ESI_AMM_OVI to OPP_ESITI_FROM_VALAR;
grant delete on OPP_ESITI_APP_ZOOT_ESI_AMM_OVI to OPP_ESITI_FROM_VALAR;

grant select on OPP_ESITI_APP_ZOOT_CTR_AMM_BOV to OPP_ESITI_FROM_VALAR;
grant insert on OPP_ESITI_APP_ZOOT_CTR_AMM_BOV to OPP_ESITI_FROM_VALAR;
grant update on OPP_ESITI_APP_ZOOT_CTR_AMM_BOV to OPP_ESITI_FROM_VALAR;
grant delete on OPP_ESITI_APP_ZOOT_CTR_AMM_BOV to OPP_ESITI_FROM_VALAR;

grant select on OPP_ESITI_APP_ZOOT_CTR_AMM_OVI to OPP_ESITI_FROM_VALAR;
grant insert on OPP_ESITI_APP_ZOOT_CTR_AMM_OVI to OPP_ESITI_FROM_VALAR;
grant update on OPP_ESITI_APP_ZOOT_CTR_AMM_OVI to OPP_ESITI_FROM_VALAR;
grant delete on OPP_ESITI_APP_ZOOT_CTR_AMM_OVI to OPP_ESITI_FROM_VALAR;

grant select on OPP_ESITI_APP_ZOOT_CTR_COND to OPP_ESITI_FROM_VALAR;
grant insert on OPP_ESITI_APP_ZOOT_CTR_COND to OPP_ESITI_FROM_VALAR;
grant update on OPP_ESITI_APP_ZOOT_CTR_COND to OPP_ESITI_FROM_VALAR;
grant delete on OPP_ESITI_APP_ZOOT_CTR_COND to OPP_ESITI_FROM_VALAR;

grant select on OPP_ESITI_APP_ESITO_RM_FIT_FER to OPP_ESITI_FROM_VALAR;
grant insert on OPP_ESITI_APP_ESITO_RM_FIT_FER to OPP_ESITI_FROM_VALAR;
grant update on OPP_ESITI_APP_ESITO_RM_FIT_FER to OPP_ESITI_FROM_VALAR;
grant delete on OPP_ESITI_APP_ESITO_RM_FIT_FER to OPP_ESITI_FROM_VALAR;

grant select on OPP_ESITI_APP_ESITO_FITFER_EXT to OPP_ESITI_FROM_VALAR;
grant insert on OPP_ESITI_APP_ESITO_FITFER_EXT to OPP_ESITI_FROM_VALAR;
grant update on OPP_ESITI_APP_ESITO_FITFER_EXT to OPP_ESITI_FROM_VALAR;
grant delete on OPP_ESITI_APP_ESITO_FITFER_EXT to OPP_ESITI_FROM_VALAR;

grant select on OPP_ESITI_APP_ESITO_IMP_EXT to OPP_ESITI_FROM_VALAR;
grant insert on OPP_ESITI_APP_ESITO_IMP_EXT to OPP_ESITI_FROM_VALAR;
grant update on OPP_ESITI_APP_ESITO_IMP_EXT to OPP_ESITI_FROM_VALAR;
grant delete on OPP_ESITI_APP_ESITO_IMP_EXT to OPP_ESITI_FROM_VALAR;

grant select on APP_ZOOT_ESI_AMM_BOV_INT to OPP_ESITI_FROM_VALAR;
grant insert on APP_ZOOT_ESI_AMM_BOV_INT to OPP_ESITI_FROM_VALAR;
grant update on APP_ZOOT_ESI_AMM_BOV_INT to OPP_ESITI_FROM_VALAR;
grant delete on APP_ZOOT_ESI_AMM_BOV_INT to OPP_ESITI_FROM_VALAR;

-- assegno il ruolo all'utente
--grant OPP_ESITI_RL_USER to OPP_ESITI_FINALUSER;


-- sinonimi pubblici

create public synonym OPP_ESITI_APP_ANAGRAFICHE FOR OPP_ESITI_ADM.OPP_ESITI_APP_ANAGRAFICHE;
create public synonym OPP_ESITI_APP_AZIENDA FOR OPP_ESITI_ADM.OPP_ESITI_APP_AZIENDA;
create public synonym OPP_ESITI_APP_CAMPIONE FOR OPP_ESITI_ADM.OPP_ESITI_APP_CAMPIONE;
create public synonym OPP_ESITI_APP_CAPI_ALLEVATI FOR OPP_ESITI_ADM.OPP_ESITI_APP_CAPI_ALLEVATI;
create public synonym OPP_ESITI_APP_CODICI_COND FOR OPP_ESITI_ADM.OPP_ESITI_APP_CODICI_COND;
create public synonym OPP_ESITI_APP_CONTROLLO FOR OPP_ESITI_ADM.OPP_ESITI_APP_CONTROLLO;
create public synonym OPP_ESITI_APP_DOMANDA FOR OPP_ESITI_ADM.OPP_ESITI_APP_DOMANDA;
create public synonym OPP_ESITI_APP_ESITO_COND FOR OPP_ESITI_ADM.OPP_ESITI_APP_ESITO_COND;
create public synonym OPP_ESITI_APP_ESITO_COND_ATTO FOR OPP_ESITI_ADM.OPP_ESITI_APP_ESITO_COND_ATTO;
create public synonym OPP_ESITI_APP_ESITO_IMPEGNI FOR OPP_ESITI_ADM.OPP_ESITI_APP_ESITO_IMPEGNI;
create public synonym OPP_ESITI_APP_ESITO_SUP FOR OPP_ESITI_ADM.OPP_ESITI_APP_ESITO_SUP;
create public synonym OPP_ESITI_APP_NATURA_2000 FOR OPP_ESITI_ADM.OPP_ESITI_APP_NATURA_2000;
create public synonym OPP_ESITI_APP_TUTELA_ACQUE FOR OPP_ESITI_ADM.OPP_ESITI_APP_TUTELA_ACQUE;
create public synonym OPP_ESITI_APP_UBA FOR OPP_ESITI_ADM.OPP_ESITI_APP_UBA;
create public synonym OPP_ESITI_APP_UBA_AMM FOR OPP_ESITI_ADM.OPP_ESITI_APP_UBA_AMM;
create public synonym OPP_ESITI_APP_UTENTI FOR OPP_ESITI_ADM.OPP_ESITI_APP_UTENTI;

create public synonym OPP_ESITI_DWH_INT_SOTTOINT FOR OPP_ESITI_ADM.OPP_ESITI_DWH_INT_SOTTOINT;
create public synonym OPP_ESITI_DWH_MATR_AMM_IDEALE FOR OPP_ESITI_ADM.OPP_ESITI_DWH_MATR_AMM_IDEALE;

create public synonym OPP_ESITI_APP_ZOOT_STATO FOR OPP_ESITI_ADM.OPP_ESITI_APP_ZOOT_STATO;
create public synonym OPP_ESITI_APP_ZOOT_ESI_AMM_BOV FOR OPP_ESITI_ADM.OPP_ESITI_APP_ZOOT_ESI_AMM_BOV;
create public synonym OPP_ESITI_APP_ZOOT_ESI_AMM_OVI FOR OPP_ESITI_ADM.OPP_ESITI_APP_ZOOT_ESI_AMM_OVI;
create public synonym OPP_ESITI_APP_ZOOT_CTR_AMM_OVI FOR OPP_ESITI_ADM.OPP_ESITI_APP_ZOOT_CTR_AMM_OVI;
create public synonym OPP_ESITI_APP_ZOOT_CTR_AMM_BOV FOR OPP_ESITI_ADM.OPP_ESITI_APP_ZOOT_CTR_AMM_BOV;
create public synonym OPP_ESITI_APP_ZOOT_CTR_COND FOR OPP_ESITI_ADM.OPP_ESITI_APP_ZOOT_CTR_COND;

create public synonym OPP_ESITI_APP_ESITO_RM_FIT_FER FOR OPP_ESITI_ADM.OPP_ESITI_APP_ESITO_RM_FIT_FER;
create public synonym OPP_ESITI_APP_ESITO_FITFER_EXT FOR OPP_ESITI_ADM.OPP_ESITI_APP_ESITO_FITFER_EXT;
create public synonym OPP_ESITI_APP_ESITO_IMP_EXT FOR OPP_ESITI_ADM.OPP_ESITI_APP_ESITO_IMP_EXT;
create public synonym APP_ZOOT_ESI_AMM_BOV_INT FOR OPP_ESITI_ADM.APP_ZOOT_ESI_AMM_BOV_INT;



--DROP PUBLIC synonym OPP_ESITI_APP_CAMPIONE


/* vedere i privilegi dei ruoli */
--select * from role_tab_privs;


/*
 * Evolutive fine 2021
 */
ALTER TABLE OPP_ESITI_ADM.OPP_ESITI_APP_AZIENDA ADD INDIRIZZO VARCHAR2(80);
ALTER TABLE OPP_ESITI_ADM.OPP_ESITI_APP_AZIENDA ADD CAP INTEGER;
ALTER TABLE OPP_ESITI_ADM.OPP_ESITI_APP_AZIENDA ADD PEC VARCHAR2(50);


